/** 75 additional travel-mood types (200 moods). */
export const EXTRA_TRAVEL_MOOD_GROUPS = [
  { label: 'City after dark', moods: ['🌃 Neon Alley', '🌃 Midnight Taxi'] },
  { label: 'Train windows', moods: ['🚆 Platform Goodbye', '🚆 Dining Car'] },
  { label: 'Island hopping', moods: ['🚤 Salt Spray', '🚤 Tidepool Hour'] },
  { label: 'Desert roads', moods: ['🐪 Dune Silence', '🐪 Mirage Mile'] },
  { label: 'Temple trails', moods: ['🛕 Bell at Dawn', '🛕 Lamp Circle'] },
  { label: 'Food markets', moods: ['🌶️ Spice Lane', '🌶️ Steam Basket'] },
  { label: 'Snow cabins', moods: ['🪵 Hearth Glow', '🪵 First Tracks'] },
  { label: 'Rain cities', moods: ['☔ Umbrella Ballet', '☔ Cobble Shine'] },
  { label: 'Safari dust', moods: ['🦁 Golden Hour Pride', '🦁 Track Dust'] },
  { label: 'River boats', moods: ['🛶 Slow Current', '🛶 Lock and Linger'] },
  { label: 'Mountain huts', moods: ['🥾 Switchback Burn', '🥾 Ridge Wind'] },
  { label: 'Coastal drives', moods: ['🚗 Cliff Radio', '🚗 Pull-off View'] },
  { label: 'Old towns', moods: ['🧭 Lost on Purpose', '🧭 Shuttered Noon'] },
  { label: 'Night markets', moods: ['🏮 Lantern Queue', '🏮 Skewer Smoke'] },
  { label: 'Vineyard days', moods: ['🍇 Row Wander', '🍇 Barrel Room'] },
  { label: 'Lake mornings', moods: ['🧣 Glass Water', '🧣 Jetty Coffee'] },
  { label: 'Jungle paths', moods: ['🦜 Canopy Call', '🦜 Waterfall Mist'] },
  { label: 'Festival nights', moods: ['🥁 Drum Circle', '🥁 Confetti Air'] },
  { label: 'Pilgrim roads', moods: ['🚶 Dawn Procession', '🚶 Hill Shrine'] },
  { label: 'Arctic light', moods: ['🌌 Polar Quiet', '🌌 Blue Ice'] },
  { label: 'Volcano country', moods: ['🌋 Black Sand', '🌋 Steam Vent'] },
  { label: 'Rice terraces', moods: ['🌾 Green Steps', '🌾 Misty Paddy'] },
  { label: 'Souk alleys', moods: ['🧿 Brass Glint', '🧿 Mint Tea'] },
  { label: 'Harbor dawns', moods: ['⚓ Rope and Gulls', '⚓ Catch Auction'] },
  { label: 'Canyon country', moods: ['🪨 Echo Walls', '🪨 Rim Trail'] },
  { label: 'Cherry blossom', moods: ['🌸 Petal Drift', '🌸 Picnic Blanket', '🌸 Brief Pink'] },
  { label: 'Monsoon mood', moods: ['🌧️ First Rain', '🌧️ Wet Asphalt', '🌧️ Break in Cloud'] },
  { label: 'Ski village', moods: ['🎿 Last Lift', '🎿 Alpine Lunch', '🎿 Aprés Glow'] },
  { label: 'Ferry crossings', moods: ['⛴️ Horn at Dawn', '⛴️ Wake Watch', '⛴️ Deck Rail'] },
  { label: 'Book towns', moods: ['📚 Stacked Stairs', '📚 Margin Notes', '📚 Reading Nook'] },
  { label: 'Street portraits', moods: ['📸 Consent Smile', '📸 Mural Pause', '📸 Shade Step'] },
  { label: 'Family voyages', moods: ['👨\u200d👩\u200d👧 Matching Hats', '👨\u200d👩\u200d👧 Jetty Cone', '👨\u200d👩\u200d👧 Shared Map'] },
  { label: 'Solo tables', moods: ['🍽️ Table for One', '🍽️ Night Notes', '🍽️ Balcony Quiet'] },
  { label: 'Luxury slow', moods: ['🛁 Marble Hour', '🛁 Suite Sunset', '🛁 Late Checkout'] },
  { label: 'Budget miles', moods: ['🎒 Hostel Bunk', '🎒 Night Bus', '🎒 Noodle Counter'] },
  { label: 'Cycling tours', moods: ['🚲 Tail Wind', '🚲 Bakery Stop', '🚲 Tent Pedal'] },
  { label: 'Dive days', moods: ['🤿 Blue Drop', '🤿 Reef Drift', '🤿 Boat Nap'] },
  { label: 'Stargazing', moods: ['🔭 Dark Sky', '🔭 Meteor Wish', '🔭 Blanket Up'] },
  { label: 'Hot springs', moods: ['♨️ Steam Silence', '♨️ Stone Pool', '♨️ Yukata Walk'] },
  { label: 'Castle towns', moods: ['🏰 Rampart View', '🏰 Guard Change', '🏰 Garden Grid'] },
  { label: 'Tea country', moods: ['🍃 Picking Mist', '🍃 Estate Cup', '🍃 Hill Rain'] },
  { label: 'Border towns', moods: ['🛂 Stamp Day', '🛂 Two Languages', '🛂 Shared Menu'] },
  { label: 'Music cities', moods: ['🎷 Corner Horn', '🎷 Late Set', '🎷 Vinyl Rain'] },
  { label: 'Architecture walks', moods: ['🏛️ Column Shade', '🏛️ Line and Light', '🏛️ Glass Canyon'] },
  { label: 'Wildlife hides', moods: ['🦉 Blind Wait', '🦉 Long Lens', '🦉 Still Breath'] },
  { label: 'Farm stays', moods: ['🐓 Rooster Alarm', '🐓 Morning Pail', '🐓 Field Edge'] },
  { label: 'Carnival color', moods: ['🎭 Feather Storm', '🎭 Street Surge', '🎭 Glitter Dust'] },
  { label: 'Winter cities', moods: ['🧣 Scarf Season', '🧣 Rink Lights', '🧣 Mitten Thaw'] },
  { label: 'Spring roads', moods: ['🌷 Verge Bloom', '🌷 Breeze Day', '🌷 Soft Rain'] },
  { label: 'Autumn trails', moods: ['🍁 Leaf Crush', '🍁 Golden Path', '🍁 Orchard Stop'] },
  { label: 'Summer nights', moods: ['🍉 Balcony Slice', '🍉 River Burst', '🍉 Late Swim'] },
  { label: 'Sacred rivers', moods: ['🌊 Ghats at Dawn', '🌊 Floating Flame', '🌊 Quiet Step'] },
  { label: 'High passes', moods: ['⛰️ Prayer Flag', '⛰️ Hairpin Climb', '⛰️ Cloud Floor'] },
  { label: 'Oasis stops', moods: ['🌴 Shade Well', '🌴 Rest Hour', '🌴 Cool Sand'] },
  { label: 'Fjord country', moods: ['🛥️ Waterfall Face', '🛥️ Wind Deck', '🛥️ Cliff Veil'] },
  { label: 'Savanna dusk', moods: ['🐘 Bush Dinner', '🐘 Wide Dark', '🐘 Crossing Hour'] },
  { label: 'Coral coasts', moods: ['🐠 Snorkel Calm', '🐠 Low Tide Walk', '🐠 Glass Sea'] },
  { label: 'Mountain rail', moods: ['🚂 Rack Climb', '🚂 Window Frost', '🚂 Tunnel Light'] },
  { label: 'Heritage walks', moods: ['🏺 Museum Pause', '🏺 Stone Story', '🏺 Courtyard Frame'] },
  { label: 'Spice ports', moods: ['🚢 Dock Scent', '🚢 Sack and Scale', '🚢 Horn Fade'] },
  { label: 'Meadow camps', moods: ['🌼 Tent Zip', '🌼 Low Flame', '🌼 Cowbell Night'] },
  { label: 'Cliff villages', moods: ['🏘️ Stacked Houses', '🏘️ Donkey Lane', '🏘️ Sea Below'] },
  { label: 'Ice hotels', moods: ['🧊 Blue Room', '🧊 Silent Hall', '🧊 Fur Bench'] },
  { label: 'Balloon dawns', moods: ['🎈 Basket Lift', '🎈 Patchwork Fields', '🎈 Thermos Air'] },
  { label: 'Cooking classes', moods: ['🔪 Market Basket', '🔪 Pan Hiss', '🔪 Shared Plate'] },
  { label: 'Language swaps', moods: ['💬 Cafe Exchange', '💬 New Word', '💬 Two Accents'] },
  { label: 'Photo walks', moods: ['📷 Golden Corner', '📷 Reflection Hunt', '📷 Slow Shutter'] },
  { label: 'Wellness retreats', moods: ['🧘 Morning Sit', '🧘 Oil and Steam', '🧘 Phone Away'] },
  { label: 'Roadside shrines', moods: ['🎀 Ribbon Tree', '🎀 Small Flame', '🎀 Brief Stop'] },
  { label: 'Harvest fairs', moods: ['🍎 Prize Pumpkin', '🍎 Fiddle Set', '🍎 Jar Stall'] },
  { label: 'Midnight bakeries', moods: ['🥐 Warm Bag', '🥐 Flour Air', '🥐 First Batch'] },
  { label: 'Lighthouse walks', moods: ['🏮 Beam Sweep', '🏮 Spray Path', '🏮 Wind Lean'] },
  { label: 'Cave country', moods: ['🕯️ Drip Hall', '🕯️ Cool Dark', '🕯️ Pool Light'] },
  { label: 'Stepwells', moods: ['🪜 Geometry Down', '🪜 Cool Depth', '🪜 Looking Up'] },
  { label: 'Houseboats', moods: ['🛏️ Still Cabin', '🛏️ Lily Drift', '🛏️ Kettle Rock'] },
] as const;
