// Cascading location data for the Create NeverBeen Account page: Country → State → City.
//
// STATES_BY_COUNTRY covers every country in SEED_COUNTRIES with real first-level
// divisions (states / provinces / regions / governorates). CITIES_BY_STATE curates
// well-known cities for popular destinations; any state without a curated list falls
// back to that country's SEED_COUNTRIES city pool, so the City dropdown is never empty.
//
// UI contract (register page): choosing a parent repopulates its children and clears
// every child selection, so the user always re-picks a valid State and City.

import { SEED_COUNTRIES } from './community-seed';

/** First-level divisions for all 184 registration countries, keyed by country name. */
export const STATES_BY_COUNTRY: Record<string, string[]> = {
  "Andorra": ["Andorra la Vella", "Canillo", "Encamp", "Escaldes-Engordany", "La Massana", "Ordino", "Sant Julià de Lòria"],
  "United Arab Emirates": ["Abu Dhabi", "Dubai", "Sharjah", "Ajman", "Umm Al Quwain", "Ras Al Khaimah", "Fujairah"],
  "Afghanistan": ["Kabul", "Herat", "Kandahar", "Balkh", "Nangarhar", "Parwan"],
  "Antigua and Barbuda": ["Saint John", "Saint Paul", "Saint Philip", "Saint Mary", "Barbuda"],
  "Albania": ["Tiranë", "Durrës", "Vlorë", "Elbasan", "Shkodër", "Korçë", "Fier", "Berat"],
  "Armenia": ["Yerevan", "Aragatsotn", "Ararat", "Armavir", "Gegharkunik", "Lori", "Syunik", "Vayots Dzor"],
  "Angola": ["Luanda", "Benguela", "Huambo", "Huíla", "Kwanza Sul", "Malanje", "Cabinda"],
  "Argentina": ["Buenos Aires", "Córdoba", "Santa Fe", "Mendoza", "Tucumán", "Salta", "Misiones", "Chubut", "Neuquén", "Río Negro"],
  "Austria": ["Vienna", "Lower Austria", "Upper Austria", "Salzburg", "Tyrol", "Vorarlberg", "Styria", "Carinthia", "Burgenland"],
  "Australia": ["New South Wales", "Victoria", "Queensland", "Western Australia", "South Australia", "Tasmania", "Australian Capital Territory", "Northern Territory"],
  "Azerbaijan": ["Baku", "Ganja", "Sumqayit", "Mingachevir", "Lankaran", "Shaki", "Nakhchivan"],
  "Bosnia and Herzegovina": ["Sarajevo", "Tuzla", "Zenica", "Mostar", "Banja Luka", "Brčko"],
  "Barbados": ["Christ Church", "Saint Michael", "Saint James", "Saint Lucy", "Saint Philip"],
  "Bangladesh": ["Dhaka", "Chattogram", "Khulna", "Rajshahi", "Sylhet", "Barishal", "Rangpur", "Mymensingh"],
  "Belgium": ["Brussels", "Antwerp", "Ghent", "Bruges", "Liège", "Namur", "Leuven", "Charleroi"],
  "Burkina Faso": ["Ouagadougou", "Bobo-Dioulasso", "Koudougou", "Ouahigouya", "Banfora", "Kaya"],
  "Bulgaria": ["Sofia City", "Sofia Province", "Plovdiv", "Varna", "Burgas", "Ruse", "Pleven", "Blagoevgrad"],
  "Bahrain": ["Capital Governorate", "Muharraq Governorate", "Northern Governorate", "Southern Governorate"],
  "Burundi": ["Bujumbura Mairie", "Bujumbura Rural", "Gitega", "Ngozi", "Ruyigi"],
  "Benin": ["Cotonou", "Porto-Novo", "Parakou", "Abomey-Calavi", "Djougou", "Bohicon"],
  "Saint Barthelemy": ["Gustavia", "Lorient", "Saint-Jean", "Corossol"],
  "Bermuda": ["Hamilton Parish", "Pembroke Parish", "Saint George's Parish", "Southampton Parish", "Devonshire Parish"],
  "Brunei": ["Brunei-Muara", "Belait", "Temburong", "Tutong"],
  "Bolivia": ["Santa Cruz", "La Paz", "Cochabamba", "Sucre", "Oruro", "Potosí", "Tarija", "Beni", "Pando"],
  "Brazil": ["São Paulo", "Rio de Janeiro", "Minas Gerais", "Bahia", "Paraná", "Rio Grande do Sul", "Pernambuco", "Ceará", "Pará", "Santa Catarina", "Goiás", "Amazonas", "Espírito Santo", "Paraíba", "Mato Grosso", "Alagoas", "Piauí", "Rio Grande do Norte", "Maranhão", "Mato Grosso do Sul", "Distrito Federal"],
  "Bahamas": ["New Providence", "Grand Bahama", "Abaco", "Exuma", "Eleuthera", "Andros"],
  "Bhutan": ["Thimphu", "Paro", "Punakha", "Bumthang", "Wangdue Phodrang", "Gelephu"],
  "Botswana": ["Gaborone", "Francistown", "Maun", "Kasane", "Serowe", "Selibe Phikwe"],
  "Belarus": ["Minsk", "Gomel", "Mogilev", "Vitebsk", "Grodno", "Brest"],
  "Belize": ["Belize District", "Cayo District", "Corozal District", "Orange Walk District", "Stann Creek District", "Toledo District"],
  "Canada": ["Ontario", "Quebec", "British Columbia", "Alberta", "Manitoba", "Saskatchewan", "Nova Scotia", "New Brunswick", "Newfoundland and Labrador", "Prince Edward Island", "Northwest Territories", "Yukon", "Nunavut"],
  "Democratic Republic of the Congo": ["Kinshasa", "Katanga", "North Kivu", "South Kivu", "Équateur", "Orientale", "Kasaï-Occidental"],
  "Central African Republic": ["Bangui", "Bamingui-Bangoran", "Basse-Kotto", "Haute-Kotto", "Mambéré-Kadéï", "Ouham"],
  "Republic of the Congo": ["Brazzaville", "Pointe-Noire", "Pool", "Bouenza", "Niari", "Lékoumou"],
  "Switzerland": ["Zürich", "Bern", "Geneva", "Vaud", "Basel-Stadt", "Basel-Landschaft", "Lucerne", "Ticino", "Valais", "Graubünden", "Aargau", "Thurgau"],
  "Cote d'Ivoire": ["Abidjan", "Yamoussoukro", "Bouaké", "San-Pédro", "Korhogo", "Daloa"],
  "Chile": ["Santiago Metropolitan", "Valparaíso", "Biobío", "La Araucanía", "Los Lagos", "Antofagasta", "Coquimbo", "Maule", "Magallanes"],
  "Cameroon": ["Douala", "Yaoundé", "Bamenda", "Bafoussam", "Garoua", "Maroua", "Limbé"],
  "China": ["Beijing", "Shanghai", "Guangdong", "Zhejiang", "Jiangsu", "Sichuan", "Hubei", "Hunan", "Fujian", "Shandong", "Henan", "Liaoning", "Shaanxi", "Yunnan", "Guangxi", "Hainan", "Chongqing", "Tianjin"],
  "Colombia": ["Bogotá D.C.", "Antioquia", "Valle del Cauca", "Atlántico", "Santander", "Bolívar", "Cundinamarca", "Nariño", "Caldas"],
  "Costa Rica": ["San José", "Alajuela", "Cartago", "Heredia", "Guanacaste", "Puntarenas", "Limón"],
  "Cuba": ["Havana", "Santiago de Cuba", "Camagüey", "Holguín", "Santa Clara", "Guantánamo", "Matanzas"],
  "Cape Verde": ["Praia", "Mindelo", "Espargos", "Assomada", "Porto Novo"],
  "Cyprus": ["Nicosia", "Limassol", "Larnaca", "Paphos", "Famagusta"],
  "Czech Republic": ["Prague", "Central Bohemia", "South Moravia", "Moravia-Silesia", "South Bohemia", "Pilsen", "Hradec Králové", "Olomouc"],
  "Germany": ["Bavaria", "Berlin", "Hamburg", "Hesse", "North Rhine-Westphalia", "Saxony", "Baden-Württemberg", "Brandenburg", "Lower Saxony", "Rhineland-Palatinate", "Schleswig-Holstein", "Thuringia", "Saxony-Anhalt", "Mecklenburg-Vorpommern", "Saarland", "Bremen"],
  "Djibouti": ["Djibouti City", "Ali Sabieh", "Dikhil", "Tadjoura", "Obock"],
  "Denmark": ["Capital Region of Denmark", "Central Denmark", "North Denmark", "Region Zealand", "Region of Southern Denmark"],
  "Dominica": ["Roseau", "Portsmouth", "Marigot", "Soufrière", "Calinago Territory"],
  "Dominican Republic": ["Santo Domingo", "Santiago", "Punta Cana", "La Romana", "Puerto Plata", "San Pedro de Macorís"],
  "Algeria": ["Algiers", "Oran", "Constantine", "Annaba", "Blida", "Sétif", "Tlemcen", "Batna"],
  "Ecuador": ["Quito", "Guayaquil", "Cuenca", "Santo Domingo", "Machala", "Loja", "Ambato", "Manta"],
  "Estonia": ["Tallinn", "Tartu", "Pärnu", "Narva", "Kohtla-Järve", "Viljandi"],
  "Egypt": ["Cairo", "Alexandria", "Giza", "Luxor", "Aswan", "Sharm El Sheikh", "Hurghada", "Port Said", "Suez"],
  "Eritrea": ["Asmara", "Keren", "Massawa", "Assab", "Mendefera"],
  "Spain": ["Madrid", "Catalonia", "Andalusia", "Valencia", "Basque Country", "Galicia", "Castile and León", "Castilla-La Mancha", "Canary Islands", "Balearic Islands", "Murcia", "Aragon", "Extremadura", "Navarre"],
  "Ethiopia": ["Addis Ababa", "Dire Dawa", "Amhara", "Oromia", "Tigray", "SNNPR", "Somali", "Afar"],
  "Fiji": ["Suva", "Nadi", "Lautoka", "Labasa", "Sigatoka"],
  "Finland": ["Uusimaa", "Southwest Finland", "Pirkanmaa", "North Ostrobothnia", "Central Finland", "Lapland", "Satakunta", "Kanta-Häme"],
  "France": ["Île-de-France", "Provence-Alpes-Côte d'Azur", "Auvergne-Rhône-Alpes", "Nouvelle-Aquitaine", "Occitanie", "Brittany", "Normandy", "Grand Est", "Hauts-de-France", "Pays de la Loire", "Bourgogne-Franche-Comté", "Centre-Val de Loire", "Corsica"],
  "Gabon": ["Libreville", "Port-Gentil", "Franceville", "Ogooué-Maritime", "Haut-Ogooué", "Woleu-Ntem"],
  "United Kingdom": ["England", "Scotland", "Wales", "Northern Ireland"],
  "Georgia": ["Tbilisi", "Batumi", "Kutaisi", "Rustavi", "Samegrelo-Zemo Svaneti", "Kakheti", "Imereti"],
  "Ghana": ["Greater Accra", "Ashanti", "Western", "Eastern", "Northern", "Volta", "Central"],
  "Grenada": ["Saint George", "Saint Andrew", "Saint David", "Saint John", "Saint Patrick"],
  "Guinea": ["Conakry", "Kankan", "Labé", "N'Zérékoré", "Kindia"],
  "Equatorial Guinea": ["Malabo", "Bata", "Ebebiyín", "Mongomo", "Evinayong"],
  "Greece": ["Attica", "Central Macedonia", "Crete", "Thessaly", "Western Greece", "Peloponnese", "Ionian Islands", "South Aegean", "Epirus", "North Aegean", "Western Macedonia", "Central Greece"],
  "Guatemala": ["Guatemala City", "Escuintla", "Quetzaltenango", "Antigua Guatemala", "Petén", "Huehuetenango"],
  "Gambia": ["Banjul", "Serekunda", "Bakau", "West Coast", "Lower River", "Central River"],
  "Guinea-Bissau": ["Bissau", "Bafatá", "Gabú", "Cacheu", "Biombo"],
  "Guyana": ["Georgetown", "Linden", "New Amsterdam", "Essequibo Islands-West Demerara", "Demerara-Mahaica"],
  "Hong Kong": ["Hong Kong Island", "Kowloon", "New Territories"],
  "Honduras": ["Tegucigalpa", "San Pedro Sula", "La Ceiba", "Choluteca", "Copán", "Atlántida"],
  "Croatia": ["Zagreb", "Split-Dalmatia", "Dubrovnik-Neretva", "Istria", "Primorje-Gorski Kotar", "Osijek-Baranja", "Zadar"],
  "Haiti": ["Port-au-Prince", "Cap-Haïtien", "Jacmel", "Gonaïves", "Les Cayes"],
  "Hungary": ["Budapest", "Pest County", "Hajdú-Bihar", "Borsod-Abaúj-Zemplén", "Csongrád-Csanád", "Győr-Moson-Sopron", "Somogy"],
  "Indonesia": ["Jakarta", "West Java", "Central Java", "East Java", "Bali", "Yogyakarta", "North Sumatra", "South Sulawesi", "West Sumatra", "Banten", "Riau", "Papua", "Kalimantan"],
  "Ireland": ["Dublin", "Cork", "Galway", "Limerick", "Waterford", "Kerry", "Mayo", "Kilkenny"],
  "Israel": ["Tel Aviv", "Jerusalem", "Haifa", "Eilat", "Nazareth", "Be'er Sheva", "Tiberias"],
  "India": ["Maharashtra", "Delhi", "Karnataka", "Tamil Nadu", "West Bengal", "Uttar Pradesh", "Gujarat", "Rajasthan", "Kerala", "Punjab", "Haryana", "Bihar", "Odisha", "Telangana", "Andhra Pradesh", "Assam", "Goa", "Himachal Pradesh", "Jammu and Kashmir", "Madhya Pradesh", "Uttarakhand", "Chhattisgarh", "Jharkhand"],
  "Iraq": ["Baghdad", "Basra", "Erbil", "Mosul", "Najaf", "Karbala", "Sulaymaniyah"],
  "Iran": ["Tehran", "Isfahan", "Mashhad", "Shiraz", "Tabriz", "Karaj", "Yazd", "Kerman"],
  "Iceland": ["Capital Region", "Southwest", "West", "Northwest", "Northeast", "South"],
  "Italy": ["Lombardy", "Lazio", "Campania", "Veneto", "Piedmont", "Emilia-Romagna", "Tuscany", "Sicily", "Puglia", "Liguria", "Sardinia", "Friuli Venezia Giulia", "Trentino-Alto Adige", "Umbria", "Marche", "Abruzzo", "Calabria", "Basilicata", "Molise", "Aosta Valley"],
  "Jamaica": ["Kingston", "Montego Bay", "Spanish Town", "Portmore", "Negril", "Ocho Rios"],
  "Jordan": ["Amman", "Irbid", "Zarqa", "Aqaba", "Petra", "Madaba"],
  "Japan": ["Tokyo", "Osaka", "Kyoto", "Hokkaido", "Aichi", "Fukuoka", "Hyogo", "Kanagawa", "Hiroshima", "Okinawa", "Nara", "Nagano", "Ishikawa"],
  "Kenya": ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret", "Malindi", "Nyeri"],
  "Kyrgyzstan": ["Bishkek", "Osh", "Jalal-Abad", "Issyk-Kul", "Talas", "Batken"],
  "Cambodia": ["Phnom Penh", "Siem Reap", "Sihanoukville", "Battambang", "Kampot", "Koh Kong"],
  "Comoros": ["Moroni", "Mutsamudu", "Fomboni", "Grande Comore", "Anjouan", "Mohéli"],
  "North Korea": ["Pyongyang", "Hamhung", "Chongjin", "Nampo", "Wonsan"],
  "South Korea": ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Jeju", "Gyeonggi", "Gangwon", "Jeolla"],
  "Kuwait": ["Al Asimah", "Hawalli", "Farwaniya", "Mubarak Al-Kabeer", "Ahmadi", "Jahra"],
  "Kazakhstan": ["Almaty", "Astana", "Shymkent", "Karaganda", "Aktobe", "Taraz", "Pavlodar"],
  "Laos": ["Vientiane", "Luang Prabang", "Savannakhet", "Pakse", "Champasak", "Luang Namtha"],
  "Lebanon": ["Beirut", "Mount Lebanon", "North Lebanon", "South Lebanon", "Baalbek", "Keserwan", "Akkar"],
  "Liechtenstein": ["Vaduz", "Schaan", "Balzers", "Triesen", "Eschen", "Mauren"],
  "Sri Lanka": ["Western Province", "Central Province", "Southern Province", "Northern Province", "Eastern Province", "Sabaragamuwa", "North Western", "North Central", "Uva"],
  "Liberia": ["Monrovia", "Gbarnga", "Buchanan", "Kakata", "Harper", "Voinjama"],
  "Lesotho": ["Maseru", "Teyateyaneng", "Mafeteng", "Hlotse", "Mohale's Hoek", "Quthing"],
  "Lithuania": ["Vilnius", "Kaunas", "Klaipėda", "Šiauliai", "Panevėžys", "Alytus", "Marijampolė"],
  "Luxembourg": ["Luxembourg City", "Esch-sur-Alzette", "Differdange", "Dudelange", "Ettelbruck", "Remich"],
  "Latvia": ["Riga", "Daugavpils", "Liepāja", "Jelgava", "Jūrmala", "Ventspils", "Valmiera"],
  "Libya": ["Tripoli", "Benghazi", "Misrata", "Sabha", "Zawiya", "Derna"],
  "Morocco": ["Casablanca", "Rabat", "Marrakesh", "Fez", "Tangier", "Agadir", "Meknes", "Oujda"],
  "Monaco": ["Monte-Carlo", "La Condamine", "Monaco-Ville", "Larvotto", "La Rousse", "Jardin Exotique"],
  "Moldova": ["Chișinău", "Bălți", "Bender", "Tiraspol", "Orhei", "Comrat"],
  "Montenegro": ["Podgorica", "Nikšić", "Herceg Novi", "Budva", "Kotor", "Bar"],
  "Madagascar": ["Antananarivo", "Toamasina", "Antsiranana", "Fianarantsoa", "Mahajanga", "Toliara"],
  "North Macedonia": ["Skopje", "Bitola", "Kumanovo", "Prilep", "Tetovo", "Ohrid", "Strumica"],
  "Mali": ["Bamako", "Ségou", "Mopti", "Timbuktu", "Koutiala", "Kayes"],
  "Myanmar": ["Yangon", "Mandalay", "Naypyidaw", "Bago", "Mawlamyine", "Monywa", "Pathein"],
  "Mongolia": ["Ulaanbaatar", "Erdenet", "Darkhan", "Choibalsan", "Ölgii", "Khovd"],
  "Mauritania": ["Nouakchott", "Nouadhibou", "Rosso", "Kiffa", "Zouérat", "Atar"],
  "Malta": ["Northern Region", "Southern Region", "Eastern Region", "Western Region", "Central Region"],
  "Maldives": ["Malé", "Addu", "Haa Alif", "Seenu", "Baa", "Raa", "Alifu Dhaalu"],
  "Malawi": ["Lilongwe", "Blantyre", "Mzuzu", "Zomba", "Mangochi", "Karonga"],
  "Mexico": ["Mexico City", "Jalisco", "Nuevo León", "Yucatán", "Quintana Roo", "Baja California", "Chiapas", "Guanajuato", "Puebla", "Oaxaca", "Chihuahua", "Sonora", "Tamaulipas", "Veracruz", "Michoacán", "Nayarit", "Querétaro", "Tlaxcala", "Coahuila", "Durango"],
  "Malaysia": ["Kuala Lumpur", "Selangor", "Penang", "Johor", "Perak", "Sarawak", "Sabah", "Melaka", "Negeri Sembilan", "Pahang", "Kedah", "Perlis", "Terengganu", "Kelantan", "Putrajaya", "Labuan"],
  "Mozambique": ["Maputo", "Matola", "Beira", "Nampula", "Chimoio", "Tete", "Inhambane"],
  "Namibia": ["Windhoek", "Walvis Bay", "Swakopmund", "Oshakati", "Rundu", "Grootfontein"],
  "Niger": ["Niamey", "Zinder", "Maradi", "Agadez", "Tahoua", "Diffa"],
  "Nigeria": ["Lagos", "Abuja", "Kano", "Ibadan", "Port Harcourt", "Benin City", "Kaduna", "Enugu", "Jos", "Calabar"],
  "Nicaragua": ["Managua", "León", "Granada", "Masaya", "Matagalpa", "Chinandega"],
  "Netherlands": ["North Holland", "South Holland", "Utrecht", "North Brabant", "Gelderland", "Groningen", "Friesland", "Limburg", "Overijssel", "Drenthe", "Flevoland", "Zeeland"],
  "Norway": ["Oslo", "Vestland", "Rogaland", "Trøndelag", "Agder", "Innlandet", "Nordland", "Troms", "Finnmark", "Møre og Romsdal", "Vestfold", "Telemark"],
  "Nepal": ["Bagmati", "Gandaki", "Lumbini", "Koshi", "Madhesh", "Karnali", "Sudurpashchim"],
  "New Zealand": ["Auckland", "Wellington", "Canterbury", "Otago", "Waikato", "Bay of Plenty", "Northland", "Tasman", "Hawke's Bay"],
  "Oman": ["Muscat", "Salalah", "Sohar", "Nizwa", "Sur", "Musandam"],
  "Panama": ["Panama City", "Colón", "David", "San Miguelito", "Bocas del Toro", "Chiriquí"],
  "Peru": ["Lima", "Cusco", "Arequipa", "Trujillo", "Cusco Region", "Piura", "Huancayo", "Iquitos", "Puno"],
  "Papua New Guinea": ["Port Moresby", "Lae", "Mount Hagen", "Madang", "Kokopo", "Wewak"],
  "Philippines": ["Metro Manila", "Cebu", "Davao", "Iloilo", "Baguio", "Bacolod", "Palawan", "Bohol", "Zamboanga"],
  "Pakistan": ["Sindh", "Punjab", "Islamabad Capital Territory", "Khyber Pakhtunkhwa", "Balochistan", "Gilgit-Baltistan", "Azad Kashmir"],
  "Poland": ["Masovia", "Lesser Poland", "Silesia", "Pomerania", "Greater Poland", "Lower Silesia", "Łódź", "Lublin", "Warmia-Masuria", "Podlasie", "Świętokrzyskie", "Opole", "Subcarpathia", "Kuyavia-Pomerania", "Lesser Poland Voivodeship", "West Pomerania"],
  "Portugal": ["Lisbon", "Porto", "Faro", "Coimbra", "Braga", "Funchal", "Évora", "Setúbal", "Aveiro"],
  "Paraguay": ["Asunción", "Central", "Alto Paraná", "Itapúa", "Caaguazú", "San Pedro"],
  "Qatar": ["Doha", "Al Wakrah", "Al Khor", "Al Rayyan", "Umm Salal", "Al Shamal"],
  "Romania": ["Bucharest", "Cluj", "Timiș", "Iași", "Constanța", "Brașov", "Sibiu", "Oradea", "Craiova", "Ploiești"],
  "Serbia": ["Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica", "Zrenjanin"],
  "Russia": ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan", "Nizhny Novgorod", "Chelyabinsk", "Samara", "Omsk", "Rostov", "Vladivostok", "Sochi", "Krasnoyarsk", "Irkutsk"],
  "Rwanda": ["Kigali", "Butare", "Gisenyi", "Ruhengeri", "Muhanga", "Huye"],
  "Saudi Arabia": ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam", "Khobar", "Abha", "Tabuk"],
  "Seychelles": ["Victoria", "Anse Boileau", "Anse Royale", "Beau Vallon", "Praslin", "La Digue"],
  "Sudan": ["Khartoum", "Omdurman", "Port Sudan", "Kassala", "El Obeid", "Nyala"],
  "Sweden": ["Stockholm", "Västra Götaland", "Skåne", "Östergötland", "Uppsala", "Blekinge", "Gotland", "Halland", "Jämtland", "Norrbotten", "Värmland", "Västerbotten"],
  "Singapore": ["Central Region", "North-East Region", "North-West Region", "East Region", "West Region"],
  "Slovenia": ["Ljubljana", "Maribor", "Celje", "Kranj", "Koper", "Novo Mesto", "Ptuj"],
  "Slovakia": ["Bratislava", "Košice", "Prešov", "Žilina", "Nitra", "Banská Bystrica", "Trnava", "Trenčín"],
  "Sierra Leone": ["Freetown", "Bo", "Kenema", "Makeni", "Port Loko", "Bonthe"],
  "Senegal": ["Dakar", "Thiès", "Kaolack", "Saint-Louis", "Ziguinchor", "Touba"],
  "Somalia": ["Mogadishu", "Hargeisa", "Kismayo", "Baidoa", "Bosaso", "Marka"],
  "Suriname": ["Paramaribo", "Lelydorp", "Nieuw Nickerie", "Moengo", "Nieuw Amsterdam"],
  "South Sudan": ["Juba", "Wau", "Malakal", "Yei", "Bor", "Rumbek"],
  "El Salvador": ["San Salvador", "Santa Ana", "San Miguel", "Soyapango", "Apopa", "Cojutepeque"],
  "Eswatini": ["Mbabane", "Manzini", "Big Bend", "Malkerns", "Nhlangano"],
  "Syria": ["Damascus", "Aleppo", "Homs", "Latakia", "Hama", "Tartus", "Idlib"],
  "Chad": ["N'Djamena", "Moundou", "Sarh", "Abéché", "Kelo", "Pala"],
  "Togo": ["Lomé", "Sokodé", "Kara", "Kpalimé", "Atakpamé", "Dapaong"],
  "Thailand": ["Bangkok", "Chiang Mai", "Phuket", "Pattaya", "Chiang Rai", "Krabi", "Khon Kaen", "Nonthaburi", "Hat Yai", "Udon Thani"],
  "Tajikistan": ["Dushanbe", "Khujand", "Kulob", "Istaravshan", "Khorugh", "Panjakent"],
  "Timor-Leste": ["Dili", "Baucau", "Suai", "Lospalos", "Maliana"],
  "Turkmenistan": ["Ashgabat", "Türkmenabat", "Daşoguz", "Mary", "Balkanabat"],
  "Tunisia": ["Tunis", "Sfax", "Sousse", "Kairouan", "Bizerte", "Gabès"],
  "Tonga": ["Nukuʻalofa", "Neiafu", "ʻEua", "Vavaʻu", "Haʻapai"],
  "Turkey": ["Istanbul", "Ankara", "İzmir", "Antalya", "Bursa", "Adana", "Konya", "Trabzon", "Gaziantep", "Eskişehir"],
  "Trinidad and Tobago": ["Port of Spain", "San Fernando", "Chaguanas", "Scarborough", "Arima", "Point Fortin"],
  "Taiwan": ["Taipei", "Kaohsiung", "Taichung", "Tainan", "Hsinchu", "Keelung", "Taoyuan"],
  "Tanzania": ["Dar es Salaam", "Dodoma", "Arusha", "Mwanza", "Zanzibar", "Mbeya", "Tanga"],
  "Ukraine": ["Kyiv", "Kharkiv", "Odesa", "Dnipro", "Lviv", "Zaporizhzhia", "Chernihiv", "Vinnytsia", "Crimea"],
  "Uganda": ["Kampala", "Jinja", "Mbarara", "Gulu", "Entebbe", "Fort Portal"],
  "United States": ["California", "New York", "Texas", "Florida", "Illinois", "Washington", "Massachusetts", "Georgia", "Colorado", "Nevada", "Hawaii", "Alaska", "Pennsylvania", "Ohio", "Michigan", "North Carolina", "Virginia", "Arizona", "Oregon", "Utah", "Tennessee", "Louisiana", "Minnesota", "Maryland", "Missouri", "Wisconsin", "Indiana", "New Jersey", "Connecticut"],
  "Uruguay": ["Montevideo", "Canelones", "Maldonado", "Salto", "Paysandú", "Colonia"],
  "Uzbekistan": ["Tashkent", "Samarkand", "Bukhara", "Namangan", "Andijan", "Nukus", "Fergana"],
  "Venezuela": ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Maracay", "Ciudad Guayana", "Barcelona"],
  "Vietnam": ["Ho Chi Minh City", "Hanoi", "Da Nang", "Hai Phong", "Can Tho", "Hue", "Nha Trang", "Vung Tau"],
  "Vanuatu": ["Port Vila", "Luganville", "Isangel", "Sola", "Craig Cove"],
  "Samoa": ["Apia", "Vaitele", "Faleula", "Siusega", "Malua"],
  "Yemen": ["Sana'a", "Aden", "Taiz", "Hodeidah", "Al Mukalla", "Ibb"],
  "South Africa": ["Gauteng", "Western Cape", "KwaZulu-Natal", "Eastern Cape", "Free State", "Limpopo", "Mpumalanga", "North West", "Northern Cape"],
  "Zambia": ["Lusaka", "Copperbelt", "Livingstone", "Ndola", "Kitwe", "Kabwe"],
  "Zimbabwe": ["Harare", "Bulawayo", "Chitungwiza", "Mutare", "Gweru", "Victoria Falls"]
};

/** Curated city lists for popular country/state pairs, keyed as country > state. */
export const CITIES_BY_STATE: Record<string, Record<string, string[]>> = {
  "United States": {
    "California": ["Los Angeles", "San Francisco", "San Diego", "San Jose", "Sacramento", "Long Beach", "Oakland"],
    "New York": ["New York City", "Buffalo", "Albany", "Rochester", "Syracuse", "Yonkers"],
    "Texas": ["Houston", "Dallas", "Austin", "San Antonio", "Fort Worth", "El Paso"],
    "Florida": ["Miami", "Orlando", "Tampa", "Jacksonville", "Key West", "Fort Lauderdale"],
    "Illinois": ["Chicago", "Springfield", "Naperville", "Peoria", "Rockford"],
    "Washington": ["Seattle", "Tacoma", "Olympia", "Spokane", "Bellevue"],
    "Massachusetts": ["Boston", "Cambridge", "Worcester", "Springfield", "Salem"],
    "Georgia": ["Atlanta", "Savannah", "Augusta", "Athens", "Macon"],
    "Colorado": ["Denver", "Boulder", "Colorado Springs", "Fort Collins", "Aspen"],
    "Nevada": ["Las Vegas", "Reno", "Henderson", "Carson City"],
    "Hawaii": ["Honolulu", "Hilo", "Kailua", "Kahului", "Lahaina"],
    "Alaska": ["Anchorage", "Juneau", "Fairbanks", "Sitka", "Ketchikan"],
    "Pennsylvania": ["Philadelphia", "Pittsburgh", "Harrisburg", "Allentown", "Erie"],
    "Ohio": ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Dayton"],
    "Michigan": ["Detroit", "Grand Rapids", "Ann Arbor", "Lansing", "Traverse City"],
    "North Carolina": ["Charlotte", "Raleigh", "Durham", "Greensboro", "Asheville"],
    "Virginia": ["Richmond", "Virginia Beach", "Arlington", "Alexandria", "Norfolk"],
    "Arizona": ["Phoenix", "Tucson", "Scottsdale", "Sedona", "Flagstaff"],
    "Oregon": ["Portland", "Eugene", "Salem", "Bend", "Astoria"],
    "Utah": ["Salt Lake City", "Park City", "Provo", "St. George", "Moab"],
    "Tennessee": ["Nashville", "Memphis", "Knoxville", "Chattanooga", "Pigeon Forge"],
    "Louisiana": ["New Orleans", "Baton Rouge", "Lafayette", "Shreveport"],
    "Minnesota": ["Minneapolis", "Saint Paul", "Duluth", "Rochester", "Bloomington"],
    "Maryland": ["Baltimore", "Annapolis", "Frederick", "Rockville"],
    "Missouri": ["St. Louis", "Kansas City", "Springfield", "Columbia"],
    "Wisconsin": ["Milwaukee", "Madison", "Green Bay", "Appleton"],
    "Indiana": ["Indianapolis", "Fort Wayne", "Bloomington", "Gary"],
    "New Jersey": ["Newark", "Jersey City", "Trenton", "Princeton", "Atlantic City"],
    "Connecticut": ["Hartford", "New Haven", "Stamford", "Bridgeport"]
  },
  "India": {
    "Maharashtra": ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad"],
    "Delhi": ["New Delhi", "Delhi"],
    "Karnataka": ["Bengaluru", "Mysuru", "Mangaluru", "Hubballi", "Manipal"],
    "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Ooty", "Kanyakumari"],
    "West Bengal": ["Kolkata", "Howrah", "Darjeeling", "Siliguri", "Shantiniketan"],
    "Uttar Pradesh": ["Lucknow", "Varanasi", "Agra", "Kanpur", "Prayagraj", "Noida"],
    "Gujarat": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Gandhinagar"],
    "Rajasthan": ["Jaipur", "Udaipur", "Jodhpur", "Jaisalmer", "Ajmer"],
    "Kerala": ["Kochi", "Thiruvananthapuram", "Kozhikode", "Munnar", "Alleppey"],
    "Punjab": ["Chandigarh", "Amritsar", "Ludhiana", "Jalandhar", "Mohali"],
    "Haryana": ["Gurugram", "Faridabad", "Panipat", "Ambala"],
    "Bihar": ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur"],
    "Odisha": ["Bhubaneswar", "Cuttack", "Puri", "Rourkela"],
    "Telangana": ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar"],
    "Andhra Pradesh": ["Visakhapatnam", "Vijayawada", "Guntur", "Tirupati"],
    "Assam": ["Guwahati", "Silchar", "Dibrugarh", "Jorhat"],
    "Goa": ["Panaji", "Margao", "Vasco da Gama", "Calangute"],
    "Himachal Pradesh": ["Shimla", "Manali", "Dharamshala", "Kullu", "Solan"],
    "Jammu and Kashmir": ["Srinagar", "Jammu", "Anantnag"],
    "Madhya Pradesh": ["Bhopal", "Indore", "Jabalpur", "Gwalior"],
    "Uttarakhand": ["Dehradun", "Haridwar", "Rishikesh", "Nainital", "Mussoorie"],
    "Chhattisgarh": ["Raipur", "Bhilai", "Bilaspur", "Korba"],
    "Jharkhand": ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro"]
  },
  "United Kingdom": {
    "England": ["London", "Manchester", "Birmingham", "Liverpool", "Bristol", "Oxford", "Cambridge", "Brighton", "York", "Bath"],
    "Scotland": ["Edinburgh", "Glasgow", "Aberdeen", "Inverness", "Stirling", "Perth"],
    "Wales": ["Cardiff", "Swansea", "Newport", "Wrexham", "Bangor"],
    "Northern Ireland": ["Belfast", "Derry", "Lisburn", "Newry", "Enniskillen"]
  },
  "France": {
    "Île-de-France": ["Paris", "Versailles", "Saint-Denis", "Boulogne-Billancourt"],
    "Provence-Alpes-Côte d'Azur": ["Marseille", "Nice", "Aix-en-Provence", "Cannes", "Antibes", "Toulon"],
    "Auvergne-Rhône-Alpes": ["Lyon", "Grenoble", "Chambéry", "Annecy", "Clermont-Ferrand"],
    "Nouvelle-Aquitaine": ["Bordeaux", "La Rochelle", "Biarritz", "Limoges", "Pau"],
    "Occitanie": ["Toulouse", "Montpellier", "Nîmes", "Perpignan", "Carcassonne"],
    "Brittany": ["Rennes", "Brest", "Lorient", "Vannes", "Saint-Malo"],
    "Normandy": ["Rouen", "Caen", "Le Havre", "Honfleur", "Bayeux"],
    "Grand Est": ["Strasbourg", "Metz", "Nancy", "Reims", "Colmar"],
    "Hauts-de-France": ["Lille", "Amiens", "Calais", "Arras"],
    "Pays de la Loire": ["Nantes", "Angers", "Le Mans", "La Baule"],
    "Bourgogne-Franche-Comté": ["Dijon", "Besançon", "Beaune", "Auxerre"],
    "Centre-Val de Loire": ["Orléans", "Tours", "Chartres", "Blois"],
    "Corsica": ["Ajaccio", "Bastia", "Calvi", "Porto-Vecchio"]
  },
  "Germany": {
    "Bavaria": ["Munich", "Nuremberg", "Augsburg", "Regensburg", "Garmisch-Partenkirchen"],
    "Berlin": ["Berlin"],
    "Hamburg": ["Hamburg"],
    "Hesse": ["Frankfurt", "Wiesbaden", "Darmstadt", "Kassel"],
    "North Rhine-Westphalia": ["Cologne", "Düsseldorf", "Dortmund", "Essen", "Bonn"],
    "Saxony": ["Dresden", "Leipzig", "Chemnitz", "Görlitz"],
    "Baden-Württemberg": ["Stuttgart", "Heidelberg", "Freiburg", "Karlsruhe", "Tübingen"],
    "Brandenburg": ["Potsdam", "Cottbus", "Brandenburg an der Havel"],
    "Lower Saxony": ["Hanover", "Braunschweig", "Goslar", "Lüneburg"],
    "Rhineland-Palatinate": ["Mainz", "Trier", "Koblenz", "Speyer"],
    "Schleswig-Holstein": ["Kiel", "Lübeck", "Flensburg"],
    "Thuringia": ["Weimar", "Erfurt", "Jena", "Gotha"],
    "Saxony-Anhalt": ["Magdeburg", "Halle", "Wittenberg"],
    "Mecklenburg-Vorpommern": ["Rostock", "Schwerin", "Stralsund", "Usedom"],
    "Saarland": ["Saarbrücken", "Neunkirchen", "Merzig"],
    "Bremen": ["Bremen", "Bremerhaven"]
  },
  "Brazil": {
    "São Paulo": ["São Paulo", "Campinas", "Santos", "Ribeirão Preto"],
    "Rio de Janeiro": ["Rio de Janeiro", "Niterói", "Petrópolis", "Búzios"],
    "Minas Gerais": ["Belo Horizonte", "Ouro Preto", "Juiz de Fora", "Uberlândia"],
    "Bahia": ["Salvador", "Ilhéus", "Feira de Santana", "Itacaré"],
    "Paraná": ["Curitiba", "Londrina", "Foz do Iguaçu", "Maringá"],
    "Rio Grande do Sul": ["Porto Alegre", "Gramado", "Pelotas", "Caxias do Sul"],
    "Pernambuco": ["Recife", "Olinda", "Caruaru", "Petrolina"],
    "Ceará": ["Fortaleza", "Sobral", "Caucaia", "Juazeiro do Norte"],
    "Pará": ["Belém", "Santarém", "Ananindeua", "Marabá"],
    "Santa Catarina": ["Florianópolis", "Balneário Camboriú", "Blumenau", "Joinville"],
    "Goiás": ["Goiânia", "Aparecida de Goiânia", "Anápolis"],
    "Distrito Federal": ["Brasília"]
  },
  "Australia": {
    "New South Wales": ["Sydney", "Newcastle", "Wollongong", "Byron Bay", "Blue Mountains"],
    "Victoria": ["Melbourne", "Geelong", "Ballarat", "Bendigo"],
    "Queensland": ["Brisbane", "Gold Coast", "Cairns", "Townsville", "Sunshine Coast"],
    "Western Australia": ["Perth", "Fremantle", "Broome", "Kalgoorlie"],
    "South Australia": ["Adelaide", "Mount Gambier", "Port Lincoln"],
    "Tasmania": ["Hobart", "Launceston", "Devonport", "Burnie"],
    "Australian Capital Territory": ["Canberra"],
    "Northern Territory": ["Darwin", "Alice Springs", "Katherine"]
  },
  "Canada": {
    "Ontario": ["Toronto", "Ottawa", "Hamilton", "London", "Niagara Falls"],
    "Quebec": ["Montreal", "Quebec City", "Gatineau", "Trois-Rivières"],
    "British Columbia": ["Vancouver", "Victoria", "Kelowna", "Whistler", "Nanaimo"],
    "Alberta": ["Calgary", "Edmonton", "Banff", "Jasper", "Lethbridge"],
    "Manitoba": ["Winnipeg", "Brandon", "Churchill"],
    "Saskatchewan": ["Regina", "Saskatoon", "Moose Jaw"],
    "Nova Scotia": ["Halifax", "Sydney", "Lunenburg"],
    "New Brunswick": ["Fredericton", "Saint John", "Moncton"],
    "Newfoundland and Labrador": ["St. John's", "Corner Brook", "Gander"],
    "Prince Edward Island": ["Charlottetown", "Summerside"],
    "Northwest Territories": ["Yellowknife", "Hay River"],
    "Yukon": ["Whitehorse", "Dawson City"],
    "Nunavut": ["Iqaluit", "Rankin Inlet"]
  },
  "China": {
    "Beijing": ["Beijing"],
    "Shanghai": ["Shanghai"],
    "Guangdong": ["Guangzhou", "Shenzhen", "Zhuhai", "Foshan", "Dongguan"],
    "Zhejiang": ["Hangzhou", "Ningbo", "Wenzhou", "Shaoxing"],
    "Jiangsu": ["Nanjing", "Suzhou", "Wuxi", "Changzhou"],
    "Sichuan": ["Chengdu", "Leshan", "Mianyang", "Yibin"],
    "Hubei": ["Wuhan", "Yichang", "Shiyan"],
    "Hunan": ["Changsha", "Zhangjiajie", "Hengyang"],
    "Fujian": ["Fuzhou", "Xiamen", "Quanzhou"],
    "Shandong": ["Qingdao", "Jinan", "Yantai", "Weifang"],
    "Henan": ["Zhengzhou", "Luoyang", "Kaifeng"],
    "Liaoning": ["Shenyang", "Dalian", "Anshan"],
    "Shaanxi": ["Xi'an", "Baoji", "Yan'an"],
    "Yunnan": ["Kunming", "Dali", "Lijiang", "Xishuangbanna"],
    "Guangxi": ["Guilin", "Nanning", "Beihai"],
    "Hainan": ["Haikou", "Sanya"],
    "Chongqing": ["Chongqing"],
    "Tianjin": ["Tianjin"]
  },
  "Japan": {
    "Tokyo": ["Shibuya", "Shinjuku", "Asakusa", "Odaiba", "Ginza"],
    "Osaka": ["Osaka", "Sakai", "Higashiosaka"],
    "Kyoto": ["Kyoto", "Uji", "Fushimi"],
    "Hokkaido": ["Sapporo", "Hakodate", "Otaru", "Furano"],
    "Aichi": ["Nagoya", "Toyota", "Okazaki"],
    "Fukuoka": ["Fukuoka", "Kitakyushu", "Kurume"],
    "Hyogo": ["Kobe", "Himeji", "Nishinomiya"],
    "Kanagawa": ["Yokohama", "Kamakura", "Odawara"],
    "Hiroshima": ["Hiroshima", "Onomichi", "Fukuyama"],
    "Okinawa": ["Naha", "Nago", "Itoman"],
    "Nara": ["Nara", "Kashihara"],
    "Nagano": ["Nagano", "Matsumoto", "Ueda"],
    "Ishikawa": ["Kanazawa", "Nanao"]
  },
  "Italy": {
    "Lombardy": ["Milan", "Bergamo", "Como", "Brescia", "Pavia"],
    "Lazio": ["Rome", "Viterbo", "Latina", "Frosinone"],
    "Campania": ["Naples", "Salerno", "Amalfi", "Caserta"],
    "Veneto": ["Venice", "Verona", "Padua", "Treviso"],
    "Piedmont": ["Turin", "Cuneo", "Novara"],
    "Emilia-Romagna": ["Bologna", "Parma", "Modena", "Rimini", "Reggio Emilia"],
    "Tuscany": ["Florence", "Pisa", "Siena", "Lucca", "Arezzo"],
    "Sicily": ["Palermo", "Catania", "Messina", "Siracusa"],
    "Puglia": ["Bari", "Lecce", "Taranto", "Brindisi"],
    "Liguria": ["Genoa", "La Spezia", "Sanremo", "Imperia"],
    "Sardinia": ["Cagliari", "Olbia", "Alghero", "Sassari"],
    "Friuli Venezia Giulia": ["Trieste", "Udine", "Pordenone"],
    "Trentino-Alto Adige": ["Trento", "Bolzano", "Merano"],
    "Umbria": ["Perugia", "Assisi", "Terni"],
    "Marche": ["Ancona", "Pesaro", "Macerata"],
    "Abruzzo": ["L'Aquila", "Pescara", "Teramo"],
    "Calabria": ["Reggio Calabria", "Catanzaro", "Cosenza"],
    "Basilicata": ["Potenza", "Matera"],
    "Molise": ["Campobasso", "Isernia"],
    "Aosta Valley": ["Aosta"]
  },
  "Spain": {
    "Madrid": ["Madrid", "Alcalá de Henares", "San Lorenzo de El Escorial"],
    "Catalonia": ["Barcelona", "Girona", "Tarragona", "Sitges", "Figueres"],
    "Andalusia": ["Seville", "Granada", "Málaga", "Córdoba", "Marbella", "Cádiz"],
    "Valencia": ["Valencia", "Alicante", "Benidorm", "Castellón"],
    "Basque Country": ["Bilbao", "San Sebastián", "Vitoria-Gasteiz"],
    "Galicia": ["Santiago de Compostela", "A Coruña", "Vigo", "Pontevedra"],
    "Castile and León": ["Valladolid", "León", "Segovia", "Salamanca"],
    "Castilla-La Mancha": ["Toledo", "Albacete", "Guadalajara"],
    "Canary Islands": ["Las Palmas", "Santa Cruz de Tenerife", "Arrecife"],
    "Balearic Islands": ["Palma", "Ibiza", "Maó"],
    "Murcia": ["Murcia", "Cartagena"],
    "Aragon": ["Zaragoza", "Huesca", "Teruel"],
    "Extremadura": ["Badajoz", "Cáceres"],
    "Navarre": ["Pamplona", "Estella"]
  },
  "Mexico": {
    "Mexico City": ["Mexico City", "Coyoacán", "Xochimilco"],
    "Jalisco": ["Guadalajara", "Puerto Vallarta", "Tequila"],
    "Nuevo León": ["Monterrey", "San Pedro Garza García"],
    "Yucatán": ["Mérida", "Izamal", "Progreso"],
    "Quintana Roo": ["Cancún", "Playa del Carmen", "Tulum", "Cozumel"],
    "Baja California": ["Tijuana", "Ensenada", "Mexicali"],
    "Chiapas": ["San Cristóbal de las Casas", "Tuxtla Gutiérrez", "Palenque"],
    "Guanajuato": ["Guanajuato", "León", "San Miguel de Allende"],
    "Puebla": ["Puebla", "Cholula", "Atlixco"],
    "Oaxaca": ["Oaxaca", "Puerto Escondido", "Mazunte"],
    "Chihuahua": ["Chihuahua", "Delicias"],
    "Sonora": ["Hermosillo", "Puerto Peñasco", "Nogales"],
    "Tamaulipas": ["Tampico", "Reynosa", "Matamoros"],
    "Veracruz": ["Veracruz", "Xalapa", "Coatzacoalcos"],
    "Michoacán": ["Morelia", "Pátzcuaro", "Uruapan"],
    "Nayarit": ["Tepic", "Bahía de Banderas"],
    "Querétaro": ["Querétaro", "Tequisquiapan"],
    "Tlaxcala": ["Tlaxcala", "Huamantla"],
    "Coahuila": ["Saltillo", "Torreón", "Piedras Negras"],
    "Durango": ["Durango", "Gómez Palacio"]
  },
  "United Arab Emirates": {
    "Abu Dhabi": ["Abu Dhabi", "Al Ain", "Madinat Zayed"],
    "Dubai": ["Dubai", "Deira"],
    "Sharjah": ["Sharjah", "Khor Fakkan", "Kalba"],
    "Ajman": ["Ajman"],
    "Umm Al Quwain": ["Umm Al Quwain"],
    "Ras Al Khaimah": ["Ras Al Khaimah"],
    "Fujairah": ["Fujairah"]
  },
  "Singapore": {
    "Central Region": ["Orchard", "Marina Bay", "Chinatown", "Clarke Quay"],
    "North-East Region": ["Serangoon", "Hougang", "Punggol"],
    "North-West Region": ["Woodlands", "Yishun", "Bukit Batok"],
    "East Region": ["Tampines", "Bedok", "Changi"],
    "West Region": ["Jurong", "Clementi", "Bukit Timah"]
  },
  "Malaysia": {
    "Kuala Lumpur": ["Kuala Lumpur", "Bukit Bintang", "KLCC"],
    "Selangor": ["Shah Alam", "Petaling Jaya", "Klang"],
    "Penang": ["George Town", "Batu Ferringhi", "Butterworth"],
    "Johor": ["Johor Bahru", "Mersing", "Skudai"],
    "Perak": ["Ipoh", "Taiping", "Lumut"],
    "Sarawak": ["Kuching", "Miri", "Sibu"],
    "Sabah": ["Kota Kinabalu", "Sandakan", "Tawau"],
    "Melaka": ["Melaka City", "Alor Gajah"],
    "Negeri Sembilan": ["Seremban", "Port Dickson"],
    "Pahang": ["Kuantan", "Temerloh"],
    "Kedah": ["Alor Setar", "Langkawi"],
    "Perlis": ["Kangar"],
    "Terengganu": ["Kuala Terengganu", "Kerteh"],
    "Kelantan": ["Kota Bharu", "Gua Musang"],
    "Putrajaya": ["Putrajaya"],
    "Labuan": ["Labuan"]
  },
  "Thailand": {
    "Bangkok": ["Bangkok", "Phra Nakhon", "Chatuchak", "Sukhumvit"],
    "Chiang Mai": ["Chiang Mai", "Mae Rim"],
    "Phuket": ["Phuket", "Patong", "Phuket Town"],
    "Pattaya": ["Bang Lamung", "Pattaya City"],
    "Chiang Rai": ["Chiang Rai", "Mae Sai"],
    "Krabi": ["Krabi", "Ao Nang", "Railay"],
    "Khon Kaen": ["Khon Kaen"],
    "Nonthaburi": ["Nonthaburi"],
    "Hat Yai": ["Songkhla"],
    "Udon Thani": ["Udon Thani"]
  },
  "South Korea": {
    "Seoul": ["Gangnam", "Hongdae", "Myeongdong", "Jongno", "Itaewon"],
    "Busan": ["Busan", "Haeundae", "Gamcheon"],
    "Incheon": ["Incheon", "Yeongjongdo"],
    "Daegu": ["Daegu"],
    "Daejeon": ["Daejeon"],
    "Gwangju": ["Gwangju"],
    "Jeju": ["Jeju City", "Seogwipo"],
    "Gyeonggi": ["Suwon", "Seongnam", "Pyeongchang"],
    "Gangwon": ["Chuncheon", "Gangneung", "Sokcho"],
    "Jeolla": ["Jeonju", "Yeosu", "Mokpo"]
  },
  "Turkey": {
    "Istanbul": ["Istanbul", "Kadıköy", "Beşiktaş", "Beyoğlu"],
    "Ankara": ["Ankara", "Çankaya"],
    "İzmir": ["İzmir", "Çeşme", "Alaçatı"],
    "Antalya": ["Antalya", "Kemer", "Side"],
    "Bursa": ["Bursa", "Mudanya"],
    "Adana": ["Adana"],
    "Konya": ["Konya"],
    "Trabzon": ["Trabzon", "Akçaabat"],
    "Gaziantep": ["Gaziantep"],
    "Eskişehir": ["Eskişehir"]
  },
  "Netherlands": {
    "North Holland": ["Amsterdam", "Haarlem", "Alkmaar"],
    "South Holland": ["Rotterdam", "The Hague", "Delft", "Leiden"],
    "Utrecht": ["Utrecht", "Amersfoort"],
    "North Brabant": ["Eindhoven", "Tilburg", "Den Bosch"],
    "Gelderland": ["Arnhem", "Nijmegen", "Apeldoorn"],
    "Groningen": ["Groningen"],
    "Friesland": ["Leeuwarden", "Sneek"],
    "Limburg": ["Maastricht", "Venlo"],
    "Overijssel": ["Zwolle", "Enschede"],
    "Drenthe": ["Assen", "Emmen"],
    "Flevoland": ["Lelystad", "Almere"],
    "Zeeland": ["Middelburg", "Goes"]
  },
  "Switzerland": {
    "Zürich": ["Zürich", "Winterthur", "Uster"],
    "Bern": ["Bern", "Interlaken", "Thun", "Biel"],
    "Geneva": ["Geneva", "Nyon"],
    "Vaud": ["Lausanne", "Montreux", "Vevey", "Yverdon"],
    "Basel-Stadt": ["Basel"],
    "Basel-Landschaft": ["Liestal", "Pratteln"],
    "Lucerne": ["Lucerne", "Weggis"],
    "Ticino": ["Lugano", "Locarno", "Bellinzona"],
    "Valais": ["Sion", "Zermatt", "Verbier", "Brig"],
    "Graubünden": ["Chur", "St. Moritz", "Davos"],
    "Aargau": ["Aarau", "Baden"],
    "Thurgau": ["Frauenfeld"]
  },
  "Argentina": {
    "Buenos Aires": ["Buenos Aires", "La Plata", "Vicente López"],
    "Córdoba": ["Córdoba", "Villa Carlos Paz"],
    "Santa Fe": ["Rosario", "Santa Fe"],
    "Mendoza": ["Mendoza", "San Rafael"],
    "Tucumán": ["San Miguel de Tucumán"],
    "Salta": ["Salta", "Cafayate"],
    "Misiones": ["Posadas", "Puerto Iguazú"],
    "Chubut": ["Rawson", "Comodoro Rivadavia"],
    "Neuquén": ["Neuquén", "San Martín de los Andes"],
    "Río Negro": ["Bariloche", "Viedma"]
  },
  "South Africa": {
    "Gauteng": ["Johannesburg", "Pretoria", "Soweto", "Sandton"],
    "Western Cape": ["Cape Town", "Stellenbosch", "George", "Hermanus"],
    "KwaZulu-Natal": ["Durban", "Pietermaritzburg", "Richards Bay"],
    "Eastern Cape": ["Gqeberha", "East London", "Makhanda"],
    "Free State": ["Bloemfontein", "Welkom"],
    "Limpopo": ["Polokwane", "Tzaneen"],
    "Mpumalanga": ["Mbombela", "Emalahleni"],
    "North West": ["Rustenburg", "Mahikeng"],
    "Northern Cape": ["Kimberley", "Upington"]
  },
  "Russia": {
    "Moscow": ["Moscow"],
    "Saint Petersburg": ["Saint Petersburg"],
    "Novosibirsk": ["Novosibirsk"],
    "Yekaterinburg": ["Yekaterinburg"],
    "Kazan": ["Kazan"],
    "Nizhny Novgorod": ["Nizhny Novgorod"],
    "Chelyabinsk": ["Chelyabinsk"],
    "Samara": ["Samara"],
    "Omsk": ["Omsk"],
    "Rostov": ["Rostov-on-Don"],
    "Vladivostok": ["Vladivostok"],
    "Sochi": ["Sochi"],
    "Krasnoyarsk": ["Krasnoyarsk"],
    "Irkutsk": ["Irkutsk"]
  },
  "Egypt": {
    "Cairo": ["Cairo", "Heliopolis", "Nasr City"],
    "Alexandria": ["Alexandria"],
    "Giza": ["Giza", "6th of October"],
    "Luxor": ["Luxor", "Esna"],
    "Aswan": ["Aswan", "Abu Simbel"],
    "Sharm El Sheikh": ["Sharm El Sheikh"],
    "Hurghada": ["Hurghada"],
    "Port Said": ["Port Said"],
    "Suez": ["Suez"]
  },
  "Greece": {
    "Attica": ["Athens", "Piraeus", "Peristeri"],
    "Central Macedonia": ["Thessaloniki", "Kavala", "Veria"],
    "Crete": ["Heraklion", "Chania", "Rethymno"],
    "Thessaly": ["Volos", "Larissa", "Trikala"],
    "Western Greece": ["Patras", "Missolonghi"],
    "Peloponnese": ["Nafplio", "Kalamata", "Sparta", "Argos"],
    "Ionian Islands": ["Corfu", "Zakynthos", "Kefalonia", "Lefkada"],
    "South Aegean": ["Mykonos", "Santorini", "Rhodes", "Paros"],
    "Epirus": ["Ioannina", "Metsovo"],
    "North Aegean": ["Lesvos", "Chios", "Samos"],
    "Western Macedonia": ["Kozani", "Grevena"],
    "Central Greece": ["Lamia", "Chalkis"]
  },
  "Portugal": {
    "Lisbon": ["Lisbon", "Sintra", "Cascais", "Setúbal"],
    "Porto": ["Porto", "Vila Nova de Gaia", "Matosinhos"],
    "Faro": ["Faro", "Lagos", "Albufeira", "Tavira", "Monte Gordo"],
    "Coimbra": ["Coimbra"],
    "Braga": ["Braga", "Guimarães"],
    "Funchal": ["Funchal", "Câmara de Lobos"],
    "Évora": ["Évora"],
    "Setúbal": ["Setúbal", "Palmela"],
    "Aveiro": ["Aveiro", "Ílhavo"]
  },
  "Poland": {
    "Masovia": ["Warsaw", "Radom", "Płock"],
    "Lesser Poland": ["Kraków", "Wieliczka", "Zakopane"],
    "Silesia": ["Katowice", "Gliwice", "Zabrze"],
    "Pomerania": ["Gdańsk", "Gdynia", "Sopot"],
    "Greater Poland": ["Poznań", "Kalisz"],
    "Lower Silesia": ["Wrocław", "Legnica", "Jelenia Góra"],
    "Łódź": ["Łódź"],
    "Lublin": ["Lublin"],
    "Warmia-Masuria": ["Olsztyn", "Elbląg"],
    "Podlasie": ["Białystok"],
    "Świętokrzyskie": ["Kielce"],
    "Opole": ["Opole"],
    "Subcarpathia": ["Rzeszów", "Krosno"],
    "Kuyavia-Pomerania": ["Bydgoszcz", "Toruń"],
    "West Pomerania": ["Szczecin", "Kołobrzeg"]
  },
  "Saudi Arabia": {
    "Riyadh": ["Riyadh"],
    "Jeddah": ["Jeddah"],
    "Mecca": ["Mecca", "Taif"],
    "Medina": ["Medina"],
    "Dammam": ["Dammam", "Al Khobar"],
    "Khobar": ["Al Khobar"],
    "Abha": ["Abha"],
    "Tabuk": ["Tabuk"]
  },
  "Kenya": {
    "Nairobi": ["Nairobi"],
    "Mombasa": ["Mombasa", "Nyali"],
    "Kisumu": ["Kisumu"],
    "Nakuru": ["Nakuru"],
    "Eldoret": ["Eldoret"],
    "Malindi": ["Malindi"],
    "Nyeri": ["Nyeri"]
  },
  "Nigeria": {
    "Lagos": ["Lagos", "Ikeja", "Victoria Island", "Lekki"],
    "Abuja": ["Abuja"],
    "Kano": ["Kano"],
    "Ibadan": ["Ibadan"],
    "Port Harcourt": ["Port Harcourt"],
    "Benin City": ["Benin City"],
    "Kaduna": ["Kaduna"],
    "Enugu": ["Enugu"],
    "Jos": ["Jos"],
    "Calabar": ["Calabar"]
  },
  "Morocco": {
    "Casablanca": ["Casablanca"],
    "Rabat": ["Rabat", "Salé"],
    "Marrakesh": ["Marrakesh"],
    "Fez": ["Fez"],
    "Tangier": ["Tangier"],
    "Agadir": ["Agadir"],
    "Meknes": ["Meknes"],
    "Oujda": ["Oujda"]
  },
  "Israel": {
    "Tel Aviv": ["Tel Aviv", "Jaffa", "Herzliya"],
    "Jerusalem": ["Jerusalem"],
    "Haifa": ["Haifa", "Akko"],
    "Eilat": ["Eilat"],
    "Nazareth": ["Nazareth"],
    "Be'er Sheva": ["Be'er Sheva"],
    "Tiberias": ["Tiberias"]
  },
  "Peru": {
    "Lima": ["Lima", "Miraflores", "Callao"],
    "Cusco": ["Cusco", "Ollantaytambo", "Urubamba"],
    "Arequipa": ["Arequipa"],
    "Trujillo": ["Trujillo"],
    "Piura": ["Piura"],
    "Huancayo": ["Huancayo"],
    "Iquitos": ["Iquitos"],
    "Puno": ["Puno", "Juliaca"]
  },
  "Colombia": {
    "Bogotá D.C.": ["Bogotá"],
    "Antioquia": ["Medellín", "Guatapé"],
    "Valle del Cauca": ["Cali", "Buenaventura"],
    "Atlántico": ["Barranquilla"],
    "Santander": ["Bucaramanga"],
    "Bolívar": ["Cartagena"],
    "Cundinamarca": ["Zipaquirá", "Villavicencio"],
    "Nariño": ["Pasto"],
    "Caldas": ["Manizales"]
  },
  "Chile": {
    "Santiago Metropolitan": ["Santiago", "Providencia"],
    "Valparaíso": ["Valparaíso", "Viña del Mar", "Quilpué"],
    "Biobío": ["Concepción", "Talcahuano"],
    "La Araucanía": ["Temuco", "Villarrica"],
    "Los Lagos": ["Puerto Montt", "Puerto Varas"],
    "Antofagasta": ["Antofagasta"],
    "Coquimbo": ["La Serena", "Coquimbo"],
    "Maule": ["Talca"],
    "Magallanes": ["Punta Arenas"]
  },
  "Philippines": {
    "Metro Manila": ["Manila", "Quezon City", "Makati", "Parañaque"],
    "Cebu": ["Cebu City", "Lapu-Lapu", "Mandaue"],
    "Davao": ["Davao City"],
    "Iloilo": ["Iloilo City"],
    "Baguio": ["Baguio"],
    "Bacolod": ["Bacolod"],
    "Palawan": ["Puerto Princesa", "El Nido", "Coron"],
    "Bohol": ["Tagbilaran", "Panglao"],
    "Zamboanga": ["Zamboanga City"]
  },
  "Vietnam": {
    "Ho Chi Minh City": ["Ho Chi Minh City", "Bình Thạnh"],
    "Hanoi": ["Hanoi", "Ba Đình"],
    "Da Nang": ["Da Nang", "Hải Châu"],
    "Hai Phong": ["Hai Phong"],
    "Can Tho": ["Can Tho"],
    "Hue": ["Hue"],
    "Nha Trang": ["Nha Trang"],
    "Vung Tau": ["Vung Tau"]
  },
  "Indonesia": {
    "Jakarta": ["Jakarta", "Menteng"],
    "West Java": ["Bandung", "Bogor", "Cirebon"],
    "Central Java": ["Semarang", "Surakarta"],
    "East Java": ["Surabaya", "Malang", "Banyuwangi"],
    "Bali": ["Denpasar", "Ubud", "Seminyak", "Kuta", "Canggu"],
    "Yogyakarta": ["Yogyakarta", "Prambanan"],
    "North Sumatra": ["Medan", "Berastagi"],
    "South Sulawesi": ["Makassar"],
    "West Sumatra": ["Padang", "Bukittinggi"],
    "Banten": ["Serang", "Tangerang"],
    "Riau": ["Pekanbaru", "Batam"],
    "Papua": ["Jayapura"],
    "Kalimantan": ["Banjarmasin", "Balikpapan", "Pontianak"]
  },
  "Ireland": {
    "Dublin": ["Dublin", "Dún Laoghaire"],
    "Cork": ["Cork", "Kinsale"],
    "Galway": ["Galway", "Clifden"],
    "Limerick": ["Limerick"],
    "Waterford": ["Waterford"],
    "Kerry": ["Killarney", "Dingle", "Tralee"],
    "Mayo": ["Westport", "Castlebar"],
    "Kilkenny": ["Kilkenny"]
  }
};

/** Placeholder shown until a country is chosen. */
export const STATE_PLACEHOLDER = 'Select State';
/** Placeholder shown until a state is chosen. */
export const CITY_PLACEHOLDER = 'Select City';

const SEED_CITIES_BY_COUNTRY: Record<string, string[]> = Object.fromEntries(
  SEED_COUNTRIES.map((c) => [c.name, c.cities.map((ct) => ct.name)])
);

/**
 * States for a country. Unknown countries (defensive — the dropdown only offers
 * SEED_COUNTRIES) fall back to generic regions so the cascade never dead-ends.
 */
export function getStatesForCountry(country: string): string[] {
  return STATES_BY_COUNTRY[country] ?? ['Central Region', 'North Region', 'South Region', 'East Region', 'West Region'];
}

/**
 * Cities for a country/state pair: curated list when available, otherwise the
 * country's seed-city pool from community-seed.ts.
 */
export function getCitiesForState(country: string, state: string): string[] {
  const curated = CITIES_BY_STATE[country]?.[state];
  if (curated && curated.length > 0) {
    return curated;
  }
  const fallback = SEED_CITIES_BY_COUNTRY[country] ?? [];
  if (fallback.length > 0) {
    return fallback;
  }
  return ['Capital City', 'North City', 'South City', 'East City', 'West City'];
}
