-- ============================================================================
-- NeverBeen Community — Supabase (PostgreSQL) schema
-- ----------------------------------------------------------------------------
-- Creates every table used by the NeverBeen Community API (.NET 7 Web API):
-- sign in / sign up (users + OAuth identities), profiles, settings, galleries,
-- journey feeds, message book, messenger, companionships, followers/following,
-- circles, notifications, login devices and moderation (reports / blocks).
--
-- How to run (Supabase):
--   1. Supabase Dashboard → SQL Editor → New query → paste this file → Run.
--   2. or: supabase db push (copy this file into supabase/migrations/ first)
--   3. or: psql "$SUPABASE_DB_URL" -f schema.sql
--
-- Identifier convention: PascalCase (quoted) — matches the EF Core entity /
-- property names used by NeverBeen.API one-to-one, so the API works against
-- this schema with no mapping surprises.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Lookup data
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "Countries" (
    "Id"          integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IsoCode2"    varchar(2)   NOT NULL,
    "Name"        varchar(100) NOT NULL,
    "PhoneCode"   varchar(8)
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_Countries_IsoCode2" ON "Countries" ("IsoCode2");

CREATE TABLE IF NOT EXISTS "Cities" (
    "Id"          integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CountryId"   integer      NOT NULL REFERENCES "Countries" ("Id") ON DELETE CASCADE,
    "Name"        varchar(100) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_Cities_Country_Name" ON "Cities" ("CountryId", "Name");

-- ---------------------------------------------------------------------------
-- Users (member profiles) + OAuth identities + settings + login devices
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "Users" (
    "Id"                        integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 20-digit public profile id ('8920153401' + zero-padded Id). Filled by the
    -- trigger below on INSERT; the API also computes it on read as a fallback.
    "UniqueId"                  varchar(20),
    "FirstName"                 varchar(100),
    "LastName"                  varchar(100),
    "FullName"                  varchar(200),
    "Email"                     varchar(256) NOT NULL,
    "Gender"                    varchar(20),
    "DateOfBirth"               timestamp without time zone,
    "CountryId"                 integer      REFERENCES "Countries" ("Id") ON DELETE SET NULL,
    "CityId"                    integer      REFERENCES "Cities" ("Id") ON DELETE SET NULL,
    "State"                     varchar(100),
    "Pincode"                   varchar(20),
    "ContactNumber"             varchar(30),
    "PostalAddress"             varchar(500),
    "AboutMe"                   varchar(2000),
    "Profession"                varchar(60),
    "Status"                    varchar(20)  NOT NULL DEFAULT 'Pending',  -- Pending | Active
    "ProfilePhotoUrl"           varchar(1024),
    "CoverPhotoUrl"             varchar(1024),
    "ExternalProfilePictureUrl" varchar(1024),
    "ProfilePhotoData"          bytea,                                    -- uploaded photo (<= 100 KB)
    "ProfilePhotoMimeType"      varchar(64),
    "CoverPhotoData"            bytea,
    "CoverPhotoMimeType"        varchar(64),
    "AboutMeDetailsJson"        text,                                     -- About Me (8 sub-sections + visibility) as JSON
    "ActiveStatus"              varchar(20)  NOT NULL DEFAULT 'Active',   -- Active|Busy|Don't Disturb|Away|Inactive|Custom
    "CustomStatusText"          varchar(30),
    "IsProfileLocked"           boolean      NOT NULL DEFAULT false,
    "IsVerified"                boolean      NOT NULL DEFAULT false,
    "VerifiedEmail"             varchar(256),
    "VerificationType"          varchar(20),                              -- work | university
    "VerifiedAtUtc"             timestamptz,
    "CreatedAtUtc"              timestamptz  NOT NULL DEFAULT now(),
    "UpdatedAtUtc"              timestamptz  NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_Users_Email"    ON "Users" ("Email");
CREATE UNIQUE INDEX IF NOT EXISTS "UX_Users_UniqueId" ON "Users" ("UniqueId");

-- Derive the 20-digit UniqueId automatically ('8920153401' + lpad(Id, 10, '0')).
CREATE OR REPLACE FUNCTION neverbeen_set_user_unique_id() RETURNS trigger AS $$
BEGIN
    IF NEW."UniqueId" IS NULL OR NEW."UniqueId" = '' THEN
        NEW."UniqueId" := '8920153401' || lpad(NEW."Id"::text, 10, '0');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS "TR_Users_UniqueId" ON "Users";
CREATE TRIGGER "TR_Users_UniqueId"
    BEFORE INSERT ON "Users"
    FOR EACH ROW EXECUTE FUNCTION neverbeen_set_user_unique_id();

CREATE TABLE IF NOT EXISTS "ExternalIdentities" (
    "Id"           bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"       integer      NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "Provider"     varchar(20)  NOT NULL,      -- Google | Facebook | Microsoft
    "ProviderKey"  varchar(256) NOT NULL,      -- stable provider-side user id
    "Email"        varchar(256),
    "CreatedAtUtc" timestamptz  NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_ExternalIdentities_Provider_Key"
    ON "ExternalIdentities" ("Provider", "ProviderKey");
CREATE INDEX IF NOT EXISTS "IX_ExternalIdentities_UserId" ON "ExternalIdentities" ("UserId");

CREATE TABLE IF NOT EXISTS "UserSettings" (
    "Id"                           bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"                       integer      NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "EmailNotificationsEnabled"    boolean      NOT NULL DEFAULT true,
    "PhoneNotificationsEnabled"    boolean      NOT NULL DEFAULT false,
    "PublicProfileEnabled"         boolean      NOT NULL DEFAULT true,
    "Theme"                        varchar(20)  NOT NULL DEFAULT 'light',
    "Timezone"                     varchar(64),
    "IsProfileLocked"              boolean      NOT NULL DEFAULT false,
    "WhoCanMessage"                varchar(20)  NOT NULL DEFAULT 'everyone',      -- everyone|companions|none
    "SearchVisibility"             boolean      NOT NULL DEFAULT true,
    "JourneyVisibility"            varchar(20)  NOT NULL DEFAULT 'public',        -- public|companions
    "SoundNotificationsEnabled"    boolean      NOT NULL DEFAULT true,
    "TwoFactorEnabled"             boolean      NOT NULL DEFAULT false,
    "TravelStyles"                 text[],
    "PreferredSeason"              varchar(40),
    "WhoCanConnect"                varchar(30)  NOT NULL DEFAULT 'everyone',      -- everyone|companions-of-companions|none
    "WhoCanVisitProfile"           varchar(20)  NOT NULL DEFAULT 'everyone',      -- everyone|companions|none
    "ShowActiveStatusTo"           varchar(20)  NOT NULL DEFAULT 'everyone',      -- everyone|companions|only-me
    "WhoCanSeeCompanionsList"      varchar(20)  NOT NULL DEFAULT 'everyone',      -- everyone|companions|only-me
    "AllowCompanionTagging"        boolean      NOT NULL DEFAULT true,
    "ApproveTagsBeforePost"        boolean      NOT NULL DEFAULT false,
    "IsVerified"                   boolean      NOT NULL DEFAULT false,
    "VerificationEmail"            varchar(256),
    "VerificationType"             varchar(20),
    "VerifiedAtUtc"                timestamptz,
    "CreatedAtUtc"                 timestamptz  NOT NULL DEFAULT now(),
    "UpdatedAtUtc"                 timestamptz  NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_UserSettings_UserId" ON "UserSettings" ("UserId");

CREATE TABLE IF NOT EXISTS "LoginDevices" (
    "Id"           varchar(64)  PRIMARY KEY,   -- client-generated device id
    "UserId"       integer      NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "Name"         varchar(120) NOT NULL,
    "Type"         varchar(20)  NOT NULL,      -- Phone | Tablet | Laptop | Desktop
    "Os"           varchar(60),
    "Browser"      varchar(60),
    "IpAddress"    varchar(45),
    "MacAddress"   varchar(32),
    "Location"     varchar(120),
    "LastSeenUtc"  timestamptz  NOT NULL DEFAULT now(),
    "IsCurrent"    boolean      NOT NULL DEFAULT false,
    "IsActive"     boolean      NOT NULL DEFAULT true,
    "Blocked"      boolean      NOT NULL DEFAULT false,
    "CreatedAtUtc" timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "IX_LoginDevices_UserId" ON "LoginDevices" ("UserId");

-- ---------------------------------------------------------------------------
-- Gallery (albums + photos)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "GalleryAlbums" (
    "Id"            integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"        integer      NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "Name"          varchar(120) NOT NULL,
    "CoverPhotoId"  bigint,                                       -- GalleryPhotos.Id (soft ref)
    "Privacy"       varchar(20)  NOT NULL DEFAULT 'public',       -- public|companions|only-me
    "IsDefault"     boolean      NOT NULL DEFAULT false,
    "CreatedAtUtc"  timestamptz  NOT NULL DEFAULT now(),
    "UpdatedAtUtc"  timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "IX_GalleryAlbums_UserId" ON "GalleryAlbums" ("UserId");

CREATE TABLE IF NOT EXISTS "GalleryPhotos" (
    "Id"           integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"       integer       NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "AlbumId"      integer       REFERENCES "GalleryAlbums" ("Id") ON DELETE SET NULL,
    "Url"          varchar(1024),                                -- Supabase Storage URL (optional)
    "PhotoData"    bytea,                                        -- raw bytes (optional, <= 100 KB)
    "MimeType"     varchar(64)   NOT NULL DEFAULT 'image/jpeg',
    "Caption"      varchar(300),
    "CreatedAtUtc" timestamptz   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "IX_GalleryPhotos_UserId"  ON "GalleryPhotos" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_GalleryPhotos_AlbumId" ON "GalleryPhotos" ("AlbumId");

-- ---------------------------------------------------------------------------
-- Message Book (community comments: posts + one level of replies) + tags
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "CommunityComments" (
    "Id"            integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Text"          varchar(2000) NOT NULL,
    "AuthorId"      integer      NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "ParentId"      integer      REFERENCES "CommunityComments" ("Id") ON DELETE RESTRICT,
    "ImageUrl"      varchar(1024),
    "LikeCount"     integer      NOT NULL DEFAULT 0,
    "DislikeCount"  integer      NOT NULL DEFAULT 0,
    "CreatedAtUtc"  timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "IX_CommunityComments_AuthorId" ON "CommunityComments" ("AuthorId");
CREATE INDEX IF NOT EXISTS "IX_CommunityComments_ParentId" ON "CommunityComments" ("ParentId");

CREATE TABLE IF NOT EXISTS "CommunityCommentTags" (
    "Id"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CommentId" integer NOT NULL REFERENCES "CommunityComments" ("Id") ON DELETE CASCADE,
    "UserId"    integer NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_CommunityCommentTags_Comment_User"
    ON "CommunityCommentTags" ("CommentId", "UserId");

CREATE TABLE IF NOT EXISTS "CommentReactions" (
    "Id"           bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CommentId"    integer     NOT NULL REFERENCES "CommunityComments" ("Id") ON DELETE CASCADE,
    "UserId"       integer     NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "ReactionType" integer     NOT NULL,     -- 1 Like, -1 Dislike, 2..11 hold reactions
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_CommentReactions_Comment_User"
    ON "CommentReactions" ("CommentId", "UserId");

-- ---------------------------------------------------------------------------
-- Journey feed (posts, custom audience, tags, reactions, nested comments)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "JourneyPosts" (
    "Id"             bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AuthorId"       integer       NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "WallOwnerId"    integer       REFERENCES "Users" ("Id") ON DELETE SET NULL,  -- set when posted on another wall
    "Text"           varchar(4000) NOT NULL,
    "ImageUrls"      text[],                                               -- 0..n attached photos
    "Location"       varchar(200),
    "Mood"           varchar(60),
    "PlaceId"        varchar(120),                                         -- Google Maps place id
    "Hashtags"       text[],
    "AudienceMode"   varchar(20)   NOT NULL DEFAULT 'public',              -- public|companions|custom|only-me
    "SharedText"     varchar(2000),                                        -- caption when sharing
    "OriginalPostId" bigint        REFERENCES "JourneyPosts" ("Id") ON DELETE SET NULL, -- share-of post
    "LikeCount"      integer       NOT NULL DEFAULT 0,
    "ShareCount"     integer       NOT NULL DEFAULT 0,
    "CommentCount"   integer       NOT NULL DEFAULT 0,
    "IsEdited"       boolean       NOT NULL DEFAULT false,
    "EditedAtUtc"    timestamptz,
    "CreatedAtUtc"   timestamptz   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "IX_JourneyPosts_AuthorId"       ON "JourneyPosts" ("AuthorId");
CREATE INDEX IF NOT EXISTS "IX_JourneyPosts_WallOwnerId"    ON "JourneyPosts" ("WallOwnerId");
CREATE INDEX IF NOT EXISTS "IX_JourneyPosts_OriginalPostId" ON "JourneyPosts" ("OriginalPostId");
CREATE INDEX IF NOT EXISTS "IX_JourneyPosts_CreatedAtUtc"   ON "JourneyPosts" ("CreatedAtUtc" DESC);

CREATE TABLE IF NOT EXISTS "JourneyPostAudienceEntries" (
    "Id"     bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PostId" bigint  NOT NULL REFERENCES "JourneyPosts" ("Id") ON DELETE CASCADE,
    "UserId" integer NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "Kind"   varchar(10) NOT NULL              -- allow | deny
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_JourneyPostAudience_Post_User_Kind"
    ON "JourneyPostAudienceEntries" ("PostId", "UserId", "Kind");

CREATE TABLE IF NOT EXISTS "JourneyPostTags" (
    "Id"     bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PostId" bigint  NOT NULL REFERENCES "JourneyPosts" ("Id") ON DELETE CASCADE,
    "UserId" integer NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_JourneyPostTags_Post_User" ON "JourneyPostTags" ("PostId", "UserId");

CREATE TABLE IF NOT EXISTS "JourneyPostReactions" (
    "Id"           bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PostId"       bigint       NOT NULL REFERENCES "JourneyPosts" ("Id") ON DELETE CASCADE,
    "UserId"       integer      NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "ReactionType" varchar(20)  NOT NULL,     -- Like|Dislike|Love|Smile|Laugh|Cry|Heart|Clapping|Confused|Shocked|Angry|Fire
    "CreatedAtUtc" timestamptz  NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_JourneyPostReactions_Post_User"
    ON "JourneyPostReactions" ("PostId", "UserId");

CREATE TABLE IF NOT EXISTS "JourneyComments" (
    "Id"           bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PostId"       bigint        NOT NULL REFERENCES "JourneyPosts" ("Id") ON DELETE CASCADE,
    "AuthorId"     integer       NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "ParentId"     bigint        REFERENCES "JourneyComments" ("Id") ON DELETE RESTRICT,
    "Text"         varchar(2000) NOT NULL,
    "ImageUrl"     varchar(1024),
    "LikeCount"    integer       NOT NULL DEFAULT 0,
    "CreatedAtUtc" timestamptz   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "IX_JourneyComments_PostId"   ON "JourneyComments" ("PostId");
CREATE INDEX IF NOT EXISTS "IX_JourneyComments_AuthorId" ON "JourneyComments" ("AuthorId");
CREATE INDEX IF NOT EXISTS "IX_JourneyComments_ParentId" ON "JourneyComments" ("ParentId");

CREATE TABLE IF NOT EXISTS "JourneyCommentReactions" (
    "Id"           bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CommentId"    bigint      NOT NULL REFERENCES "JourneyComments" ("Id") ON DELETE CASCADE,
    "UserId"       integer     NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "ReactionType" varchar(20) NOT NULL,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_JourneyCommentReactions_Comment_User"
    ON "JourneyCommentReactions" ("CommentId", "UserId");

-- ---------------------------------------------------------------------------
-- Companionships + followers / following
-- ---------------------------------------------------------------------------

-- One row per traveler pair. UserId < CompanionId (normalised by the API).
-- RequesterId is the member who sent the request; direction is derived from it.
CREATE TABLE IF NOT EXISTS "Companionships" (
    "Id"             bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"         integer     NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "CompanionId"    integer     NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "RequesterId"    integer     NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "Status"         varchar(20) NOT NULL DEFAULT 'pending',   -- pending | connected
    "RequestedAtUtc" timestamptz NOT NULL DEFAULT now(),
    "ConnectedAtUtc" timestamptz,
    "CreatedAtUtc"   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "CK_Companionships_Ordered" CHECK ("UserId" < "CompanionId")
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_Companionships_Pair" ON "Companionships" ("UserId", "CompanionId");
CREATE INDEX IF NOT EXISTS "IX_Companionships_CompanionId" ON "Companionships" ("CompanionId");
CREATE INDEX IF NOT EXISTS "IX_Companionships_Status"      ON "Companionships" ("Status");

CREATE TABLE IF NOT EXISTS "Follows" (
    "Id"           bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FollowerId"   integer     NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "FolloweeId"   integer     NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_Follows_Follower_Followee" ON "Follows" ("FollowerId", "FolloweeId");
CREATE INDEX IF NOT EXISTS "IX_Follows_FolloweeId" ON "Follows" ("FolloweeId");

-- ---------------------------------------------------------------------------
-- Circles (travel circles + group chat)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "Circles" (
    "Id"            integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"          varchar(120) NOT NULL,
    "Description"   varchar(500),
    "Icon"          varchar(60),
    "Color"         varchar(20),
    "PhotoUrl"      varchar(1024),
    "OwnerId"       integer      NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "CreatedAtUtc"  timestamptz  NOT NULL DEFAULT now(),
    "ArchivedAtUtc" timestamptz
);

CREATE INDEX IF NOT EXISTS "IX_Circles_OwnerId" ON "Circles" ("OwnerId");

CREATE TABLE IF NOT EXISTS "CircleMembers" (
    "Id"         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CircleId"   integer     NOT NULL REFERENCES "Circles" ("Id") ON DELETE CASCADE,
    "UserId"     integer     NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "IsAdmin"    boolean     NOT NULL DEFAULT false,
    "JoinedAtUtc" timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_CircleMembers_Circle_User" ON "CircleMembers" ("CircleId", "UserId");
CREATE INDEX IF NOT EXISTS "IX_CircleMembers_UserId" ON "CircleMembers" ("UserId");

CREATE TABLE IF NOT EXISTS "CircleMessages" (
    "Id"               bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CircleId"         integer      NOT NULL REFERENCES "Circles" ("Id") ON DELETE CASCADE,
    "SenderId"         integer      NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "Text"             varchar(2000) NOT NULL,
    "SentAtUtc"        timestamptz  NOT NULL DEFAULT now(),
    "ReplyToMessageId" bigint       REFERENCES "CircleMessages" ("Id") ON DELETE SET NULL,
    "Reactions"        text         -- JSON map: { "👍": 2, "🔥": 1 }
);

CREATE INDEX IF NOT EXISTS "IX_CircleMessages_CircleId" ON "CircleMessages" ("CircleId", "SentAtUtc");

-- ---------------------------------------------------------------------------
-- Messenger (1:1 and group conversations)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "Conversations" (
    "Id"           bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IsGroup"      boolean     NOT NULL DEFAULT false,
    "CircleId"     integer     REFERENCES "Circles" ("Id") ON DELETE SET NULL,
    "OwnerId"      integer     REFERENCES "Users" ("Id") ON DELETE SET NULL,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "IX_Conversations_CircleId" ON "Conversations" ("CircleId");

CREATE TABLE IF NOT EXISTS "ConversationParticipants" (
    "Id"                bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ConversationId"    bigint      NOT NULL REFERENCES "Conversations" ("Id") ON DELETE CASCADE,
    "UserId"            integer     NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "LastReadMessageId" bigint,                                    -- drives unread counts
    "JoinedAtUtc"       timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_ConversationParticipants_Conversation_User"
    ON "ConversationParticipants" ("ConversationId", "UserId");
CREATE INDEX IF NOT EXISTS "IX_ConversationParticipants_UserId" ON "ConversationParticipants" ("UserId");

CREATE TABLE IF NOT EXISTS "ChatMessages" (
    "Id"               bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ConversationId"   bigint        NOT NULL REFERENCES "Conversations" ("Id") ON DELETE CASCADE,
    "SenderId"         integer       NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "Text"             varchar(2000) NOT NULL,
    "SentAtUtc"        timestamptz   NOT NULL DEFAULT now(),
    "ReplyToMessageId" bigint        REFERENCES "ChatMessages" ("Id") ON DELETE SET NULL,
    "Reactions"        text          -- JSON map: { "👍": 2 }
);

CREATE INDEX IF NOT EXISTS "IX_ChatMessages_Conversation" ON "ChatMessages" ("ConversationId", "SentAtUtc");
CREATE INDEX IF NOT EXISTS "IX_ChatMessages_SenderId"      ON "ChatMessages" ("SenderId");

-- ---------------------------------------------------------------------------
-- Notifications
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "Notifications" (
    "Id"           bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"       integer      NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "Type"         varchar(40)  NOT NULL,   -- companionship_request|companionship_accepted|journey_like|journey_comment|...
    "FromUserId"   integer      NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "Message"      varchar(500) NOT NULL,
    "IsRead"       boolean      NOT NULL DEFAULT false,
    "RequestId"    bigint,                  -- companionship id / post id the notification refers to
    "Status"       varchar(20),             -- pending | approved | rejected
    "CreatedAtUtc" timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "IX_Notifications_UserId" ON "Notifications" ("UserId", "IsRead", "CreatedAtUtc" DESC);

-- ---------------------------------------------------------------------------
-- Moderation (abuse reports, blocks, hidden posts)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "AbuseReports" (
    "Id"                bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TargetType"        varchar(20)  NOT NULL,     -- post | comment | message
    "TargetId"          bigint       NOT NULL,
    "ReportedAuthorId"  integer      NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "ReportedByUserId"  integer      NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "Reason"            varchar(200) NOT NULL,
    "Details"           varchar(2000),
    "ReporterEmail"     varchar(256),
    "Status"            varchar(20)  NOT NULL DEFAULT 'pending',   -- pending | reviewed
    "CreatedAtUtc"      timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "IX_AbuseReports_Status" ON "AbuseReports" ("Status", "CreatedAtUtc" DESC);

CREATE TABLE IF NOT EXISTS "BlockedUsers" (
    "Id"             bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"         integer     NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "BlockedUserId"  integer     NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "CreatedAtUtc"   timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_BlockedUsers_User_Blocked" ON "BlockedUsers" ("UserId", "BlockedUserId");

CREATE TABLE IF NOT EXISTS "HiddenPosts" (
    "Id"           bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"       integer     NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "PostId"       bigint      NOT NULL REFERENCES "JourneyPosts" ("Id") ON DELETE CASCADE,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_HiddenPosts_User_Post" ON "HiddenPosts" ("UserId", "PostId");

-- ---------------------------------------------------------------------------
-- updated_at maintenance
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION neverbeen_set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW."UpdatedAtUtc" := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS "TR_Users_UpdatedAt" ON "Users";
CREATE TRIGGER "TR_Users_UpdatedAt"
    BEFORE UPDATE ON "Users"
    FOR EACH ROW EXECUTE FUNCTION neverbeen_set_updated_at();

DROP TRIGGER IF EXISTS "TR_UserSettings_UpdatedAt" ON "UserSettings";
CREATE TRIGGER "TR_UserSettings_UpdatedAt"
    BEFORE UPDATE ON "UserSettings"
    FOR EACH ROW EXECUTE FUNCTION neverbeen_set_updated_at();

DROP TRIGGER IF EXISTS "TR_GalleryAlbums_UpdatedAt" ON "GalleryAlbums";
CREATE TRIGGER "TR_GalleryAlbums_UpdatedAt"
    BEFORE UPDATE ON "GalleryAlbums"
    FOR EACH ROW EXECUTE FUNCTION neverbeen_set_updated_at();
