/* eslint-disable */
/**
 * Generated by scripts/generate-collection.mjs — do not edit by hand.
 * Source: sample photographs from public/audience (public/collection is empty)
 * Regenerate with: npm run generate:collection
 */

export interface CollectionPhoto {
  /** Public URL of the photograph. */
  src: string;
  /** Short display name. */
  title: string;
  /** One-line description shown under the enlarged photograph. */
  caption: string;
  /** Accessible description. */
  alt: string;
  /** Album heading; empty string keeps the photograph in the main grid. */
  album: string;
}

export const collectionPhotos: CollectionPhoto[] = [
  {
    src: '/audience/couples.jpg',
    title: 'Couples',
    caption: 'Sample studio photograph',
    alt: 'Couples — NeverBeen sample photograph',
    album: 'Audience stories',
  },
  {
    src: '/audience/families.jpg',
    title: 'Families',
    caption: 'Sample studio photograph',
    alt: 'Families — NeverBeen sample photograph',
    album: 'Audience stories',
  },
  {
    src: '/audience/birthday.jpg',
    title: 'Birthday gifts',
    caption: 'Sample studio photograph',
    alt: 'Birthday gifts — NeverBeen sample photograph',
    album: 'Audience stories',
  },
  {
    src: '/audience/social.jpg',
    title: 'Social media show-offs',
    caption: 'Sample studio photograph',
    alt: 'Social media show-offs — NeverBeen sample photograph',
    album: 'Audience stories',
  },
  {
    src: '/audience/dream-destinations.jpg',
    title: 'Dream destinations',
    caption: 'Sample studio photograph',
    alt: 'Dream destinations — NeverBeen sample photograph',
    album: 'Audience stories',
  },
  {
    src: '/audience/creators.jpg',
    title: 'Content creators',
    caption: 'Sample studio photograph',
    alt: 'Content creators — NeverBeen sample photograph',
    album: 'Audience stories',
  },
  {
    src: '/audience/golden-years.jpg',
    title: 'Golden years',
    caption: 'Sample studio photograph',
    alt: 'Golden years — NeverBeen sample photograph',
    album: 'Audience stories',
  },
  {
    src: '/audience/privacy.jpg',
    title: 'Your privacy, in writing',
    caption: 'Sample studio photograph',
    alt: 'Your privacy, in writing — NeverBeen sample photograph',
    album: 'Studio',
  },
];
