import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { firstValueFrom } from 'rxjs';
import { feedSourceCredentials } from '../models/travel-feeds';

export interface GoogleMapLocation {
  placeId: string;
  name: string;
  formattedAddress: string;
  city: string;
  country: string;
  countryCode?: string;
  latitude: number;
  longitude: number;
  mapsUrl: string;
  category?: string;
}

export const VERIFIED_GOOGLE_MAP_LOCATIONS: GoogleMapLocation[] = [
  // Europe
  {
    placeId: 'ChIJD7fiBh9u5kcRYJSMaMOCCwQ',
    name: 'Paris',
    formattedAddress: 'Paris, Île-de-France, France',
    city: 'Paris',
    country: 'France',
    countryCode: 'FR',
    latitude: 48.8566,
    longitude: 2.3522,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=48.8566,2.3522',
    category: 'City',
  },
  {
    placeId: 'ChIJLU7jZClu5kcR4PcOOO6pZMw',
    name: 'Eiffel Tower',
    formattedAddress: 'Champ de Mars, 5 Av. Anatole France, 75007 Paris, France',
    city: 'Paris',
    country: 'France',
    countryCode: 'FR',
    latitude: 48.8584,
    longitude: 2.2945,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=48.8584,2.2945',
    category: 'Landmark',
  },
  {
    placeId: 'ChIJb6e9Tz_h1EcR_mN0a5W48Vw',
    name: 'Montmartre',
    formattedAddress: 'Montmartre, 75018 Paris, France',
    city: 'Paris',
    country: 'France',
    countryCode: 'FR',
    latitude: 48.8867,
    longitude: 2.3431,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=48.8867,2.3431',
    category: 'District',
  },
  {
    placeId: 'ChIJ2V-Mo_l1nkcRfZixfUq4DAE',
    name: 'Rome',
    formattedAddress: 'Rome, Metropolitan City of Rome Capital, Italy',
    city: 'Rome',
    country: 'Italy',
    countryCode: 'IT',
    latitude: 41.9028,
    longitude: 12.4964,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=41.9028,12.4964',
    category: 'City',
  },
  {
    placeId: 'ChIJ1y6595FhKhMRmXlG0B1v0jM',
    name: 'Colosseum',
    formattedAddress: 'Piazza del Colosseo, 1, 00184 Roma RM, Italy',
    city: 'Rome',
    country: 'Italy',
    countryCode: 'IT',
    latitude: 41.8902,
    longitude: 12.4922,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=41.8902,12.4922',
    category: 'Monument',
  },
  {
    placeId: 'ChIJu_VjN73ZfEcRZgY_a-mI3QY',
    name: 'Lake Como',
    formattedAddress: 'Lake Como, Lombardy, Italy',
    city: 'Como',
    country: 'Italy',
    countryCode: 'IT',
    latitude: 45.9867,
    longitude: 9.2562,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=45.9867,9.2562',
    category: 'Nature',
  },
  {
    placeId: 'ChIJW3s6Z6vWfEcRk6v52L5vX4M',
    name: 'Bellagio',
    formattedAddress: 'Bellagio, 22021 Province of Como, Italy',
    city: 'Bellagio',
    country: 'Italy',
    countryCode: 'IT',
    latitude: 45.9872,
    longitude: 9.2626,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=45.9872,9.2626',
    category: 'Village',
  },
  {
    placeId: 'ChIJQdfh0mZfJRMR-0s4B5G1g4s',
    name: 'Positano',
    formattedAddress: 'Positano, 84017 Province of Salerno, Italy',
    city: 'Positano',
    country: 'Italy',
    countryCode: 'IT',
    latitude: 40.6281,
    longitude: 14.4850,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=40.6281,14.4850',
    category: 'Coast',
  },
  {
    placeId: 'ChIJYWJgY22vRhIR27_MhT5zG2Y',
    name: 'Amalfi Coast',
    formattedAddress: 'Amalfi Coast, Campania, Italy',
    city: 'Amalfi',
    country: 'Italy',
    countryCode: 'IT',
    latitude: 40.6340,
    longitude: 14.6027,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=40.6340,14.6027',
    category: 'Region',
  },
  {
    placeId: 'ChIJD7fiBh9u5kcRYJSMaMOCCwZ',
    name: 'Venice',
    formattedAddress: 'Venice, Metropolitan City of Venice, Italy',
    city: 'Venice',
    country: 'Italy',
    countryCode: 'IT',
    latitude: 45.4408,
    longitude: 12.3155,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=45.4408,12.3155',
    category: 'City',
  },
  {
    placeId: 'ChIJd_745g73fEcR3r31-8p8Y4c',
    name: 'Lauterbrunnen',
    formattedAddress: 'Lauterbrunnen, Canton of Bern, Switzerland',
    city: 'Lauterbrunnen',
    country: 'Switzerland',
    countryCode: 'CH',
    latitude: 46.5935,
    longitude: 7.9090,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=46.5935,7.9090',
    category: 'Alps',
  },
  {
    placeId: 'ChIJVX4fRjT0fEcRBV0w3P0Bf4g',
    name: 'Zermatt & Matterhorn',
    formattedAddress: 'Zermatt, Canton of Valais, Switzerland',
    city: 'Zermatt',
    country: 'Switzerland',
    countryCode: 'CH',
    latitude: 45.9763,
    longitude: 7.7491,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=45.9763,7.7491',
    category: 'Alps',
  },
  {
    placeId: 'ChIJS6zB3L1vfxMRZ7lS4N_9j0A',
    name: 'Santorini',
    formattedAddress: 'Santorini, Thira, South Aegean, Greece',
    city: 'Oia',
    country: 'Greece',
    countryCode: 'GR',
    latitude: 36.3932,
    longitude: 25.4615,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=36.3932,25.4615',
    category: 'Island',
  },
  {
    placeId: 'ChIJ5TCOcRaYpBIRCmZHTz37sEQ',
    name: 'Barcelona',
    formattedAddress: 'Barcelona, Catalonia, Spain',
    city: 'Barcelona',
    country: 'Spain',
    countryCode: 'ES',
    latitude: 41.3879,
    longitude: 2.1699,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=41.3879,2.1699',
    category: 'City',
  },
  {
    placeId: 'ChIJ2VaaavSpHkURUPshf8q24kU',
    name: 'Sagrada Familia',
    formattedAddress: 'Carrer de Mallorca, 401, 08013 Barcelona, Spain',
    city: 'Barcelona',
    country: 'Spain',
    countryCode: 'ES',
    latitude: 41.4036,
    longitude: 2.1744,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=41.4036,2.1744',
    category: 'Landmark',
  },
  {
    placeId: 'ChIJdd4hrwug2EcRmSrV3Vo6llI',
    name: 'London',
    formattedAddress: 'London, Greater London, United Kingdom',
    city: 'London',
    country: 'United Kingdom',
    countryCode: 'GB',
    latitude: 51.5074,
    longitude: -0.1278,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=51.5074,-0.1278',
    category: 'City',
  },
  {
    placeId: 'ChIJs8hZ5q2r2EcRYx_f4c-f0wQ',
    name: 'Big Ben & Westminster',
    formattedAddress: 'Westminster, London SW1A 0AA, United Kingdom',
    city: 'London',
    country: 'United Kingdom',
    countryCode: 'GB',
    latitude: 51.5007,
    longitude: -0.1246,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=51.5007,-0.1246',
    category: 'Landmark',
  },
  {
    placeId: 'ChIJ-b5qpqTk1UcRkJm-mXf4f4g',
    name: 'Reykjavik',
    formattedAddress: 'Reykjavik, Capital Region, Iceland',
    city: 'Reykjavik',
    country: 'Iceland',
    countryCode: 'IS',
    latitude: 64.1466,
    longitude: -21.9426,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=64.1466,-21.9426',
    category: 'Nordic',
  },
  {
    placeId: 'ChIJL67q5fNf1UcR1e4_Y-f9j0Y',
    name: 'Blue Lagoon',
    formattedAddress: 'Norðurljósavegur 9, 240 Grindavík, Iceland',
    city: 'Grindavík',
    country: 'Iceland',
    countryCode: 'IS',
    latitude: 63.8804,
    longitude: -22.4495,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=63.8804,-22.4495',
    category: 'Nature',
  },

  // Asia
  {
    placeId: 'ChIJ513GhmsWAWARi3WmflghL4w',
    name: 'Tokyo',
    formattedAddress: 'Tokyo, Japan',
    city: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    latitude: 35.6762,
    longitude: 139.6503,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=35.6762,139.6503',
    category: 'City',
  },
  {
    placeId: 'ChIJ19a-9eSPGGAR3n2Z2N5x6pQ',
    name: 'Shibuya Crossing',
    formattedAddress: 'Dogenzaka, Shibuya City, Tokyo 150-0043, Japan',
    city: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    latitude: 35.6595,
    longitude: 139.7005,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=35.6595,139.7005',
    category: 'Landmark',
  },
  {
    placeId: 'ChIJ8XJjO83V_18R_v196gMhJ24',
    name: 'Kyoto',
    formattedAddress: 'Kyoto, Kyoto Prefecture, Japan',
    city: 'Kyoto',
    country: 'Japan',
    countryCode: 'JP',
    latitude: 35.0116,
    longitude: 135.7681,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=35.0116,135.7681',
    category: 'Heritage',
  },
  {
    placeId: 'ChIJl7x7M-7t_18R2oE_yWz8j0w',
    name: 'Arashiyama Bamboo Grove',
    formattedAddress: 'Sagatenryuji Utanochicho, Ukyo Ward, Kyoto, 616-8385, Japan',
    city: 'Kyoto',
    country: 'Japan',
    countryCode: 'JP',
    latitude: 35.0170,
    longitude: 135.6713,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=35.0170,135.6713',
    category: 'Nature',
  },
  {
    placeId: 'ChIJ0xMyu03V_18RB46p5Y6t4kQ',
    name: 'Fushimi Inari Taisha',
    formattedAddress: '68 Fukakusa Yabunouchicho, Fushimi Ward, Kyoto, 612-0882, Japan',
    city: 'Kyoto',
    country: 'Japan',
    countryCode: 'JP',
    latitude: 34.9671,
    longitude: 135.7727,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=34.9671,135.7727',
    category: 'Temple',
  },
  {
    placeId: 'ChIJV4kvoDBl-DUR80GQJE-C1Q4',
    name: 'Bali',
    formattedAddress: 'Bali, Indonesia',
    city: 'Denpasar',
    country: 'Indonesia',
    countryCode: 'ID',
    latitude: -8.4095,
    longitude: 115.1889,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=-8.4095,115.1889',
    category: 'Island',
  },
  {
    placeId: 'ChIJX9a-7zTj-DUR2g7Y2c78f4M',
    name: 'Ubud',
    formattedAddress: 'Ubud, Gianyar Regency, Bali, Indonesia',
    city: 'Ubud',
    country: 'Indonesia',
    countryCode: 'ID',
    latitude: -8.5069,
    longitude: 115.2625,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=-8.5069,115.2625',
    category: 'Culture',
  },
  {
    placeId: 'ChIJ2V-Mo_l1nkcRfZixfUq4DGE',
    name: 'Singapore',
    formattedAddress: 'Singapore',
    city: 'Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    latitude: 1.3521,
    longitude: 103.8198,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=1.3521,103.8198',
    category: 'City',
  },
  {
    placeId: 'ChIJ8V9h2aY92jERQ40e9Vz9b4g',
    name: 'Bangkok',
    formattedAddress: 'Bangkok, Thailand',
    city: 'Bangkok',
    country: 'Thailand',
    countryCode: 'TH',
    latitude: 13.7563,
    longitude: 100.5018,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=13.7563,100.5018',
    category: 'City',
  },
  {
    placeId: 'ChIJv8-p56082jER5n0z5a7x4tQ',
    name: 'Chiang Mai',
    formattedAddress: 'Chiang Mai, Mueang Chiang Mai District, Chiang Mai, Thailand',
    city: 'Chiang Mai',
    country: 'Thailand',
    countryCode: 'TH',
    latitude: 18.7883,
    longitude: 98.9853,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=18.7883,98.9853',
    category: 'Culture',
  },

  // Americas
  {
    placeId: 'ChIJOwg_06VPwokRYv534QaPC8g',
    name: 'New York City',
    formattedAddress: 'New York, NY, United States',
    city: 'New York',
    country: 'United States',
    countryCode: 'US',
    latitude: 40.7128,
    longitude: -74.0060,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=40.7128,-74.0060',
    category: 'City',
  },
  {
    placeId: 'ChIJ4zGFAZpYwokRGUGphPhAn3M',
    name: 'Central Park',
    formattedAddress: 'Central Park, New York, NY, United States',
    city: 'New York',
    country: 'United States',
    countryCode: 'US',
    latitude: 40.7829,
    longitude: -73.9654,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=40.7829,-73.9654',
    category: 'Park',
  },
  {
    placeId: 'ChIJIQBpAG2ahYAR_6128GcTUEo',
    name: 'San Francisco',
    formattedAddress: 'San Francisco, CA, United States',
    city: 'San Francisco',
    country: 'United States',
    countryCode: 'US',
    latitude: 37.7749,
    longitude: -122.4194,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=37.7749,-122.4194',
    category: 'City',
  },
  {
    placeId: 'ChIJV4kvoDBl-DUR80GQJE-C1C4',
    name: 'Machu Picchu',
    formattedAddress: '08680, Peru',
    city: 'Aguas Calientes',
    country: 'Peru',
    countryCode: 'PE',
    latitude: -13.1631,
    longitude: -72.5450,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=-13.1631,-72.5450',
    category: 'Wonder',
  },
  {
    placeId: 'ChIJL68p5fNf1UcR1e4_Y-f9j0R',
    name: 'Rio de Janeiro',
    formattedAddress: 'Rio de Janeiro, State of Rio de Janeiro, Brazil',
    city: 'Rio de Janeiro',
    country: 'Brazil',
    countryCode: 'BR',
    latitude: -22.9068,
    longitude: -43.1729,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=-22.9068,-43.1729',
    category: 'City',
  },

  // Middle East & Africa & Oceania
  {
    placeId: 'ChIJv8-p56082jER5n0z5a7x4tD',
    name: 'Dubai',
    formattedAddress: 'Dubai, United Arab Emirates',
    city: 'Dubai',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    latitude: 25.2048,
    longitude: 55.2708,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=25.2048,55.2708',
    category: 'City',
  },
  {
    placeId: 'ChIJ2V-Mo_l1nkcRfZixfUq4DAU',
    name: 'Burj Khalifa',
    formattedAddress: '1 Sheikh Mohammed bin Rashid Blvd, Downtown Dubai, Dubai, UAE',
    city: 'Dubai',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    latitude: 25.1972,
    longitude: 55.2744,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=25.1972,55.2744',
    category: 'Skyscraper',
  },
  {
    placeId: 'ChIJcwL6T7SpQxQRsnG19po8b4g',
    name: 'Cairo & Pyramids of Giza',
    formattedAddress: 'Al Haram, Giza Governorate 3512201, Egypt',
    city: 'Cairo',
    country: 'Egypt',
    countryCode: 'EG',
    latitude: 29.9792,
    longitude: 31.1342,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=29.9792,31.1342',
    category: 'Wonder',
  },
  {
    placeId: 'ChIJyeZATTan1moR0aOikxC6Awk',
    name: 'Sydney',
    formattedAddress: 'Sydney, New South Wales, Australia',
    city: 'Sydney',
    country: 'Australia',
    countryCode: 'AU',
    latitude: -33.8688,
    longitude: 151.2093,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=-33.8688,151.2093',
    category: 'City',
  },
  {
    placeId: 'ChIJ42Ff0OeuEmsR1c88V6f7_0A',
    name: 'Sydney Opera House',
    formattedAddress: 'Bennelong Point, Sydney NSW 2000, Australia',
    city: 'Sydney',
    country: 'Australia',
    countryCode: 'AU',
    latitude: -33.8568,
    longitude: 151.2153,
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=-33.8568,151.2153',
    category: 'Landmark',
  },
];

@Injectable({
  providedIn: 'root',
})
export class GoogleMapsService {
  private readonly http = inject(HttpClient, { optional: true });

  /**
   * Auto search locations from Google Maps API matching user typed query.
   * Filters and suggests verified destinations. Only available items can be selected.
   */
  async searchLocations(query: string): Promise<GoogleMapLocation[]> {
    const q = query.trim().toLowerCase();
    if (!q || q.length < 2) return [];

    // If Google Places API key is present and browser supports network request, attempt Google Maps API Places lookup
    if (feedSourceCredentials.googlePlacesApiKey && this.http) {
      try {
        const url = `https://maps.googleapis.com/maps/api/place/autocomplete/json?input=${encodeURIComponent(
          q,
        )}&types=(regions)&key=${feedSourceCredentials.googlePlacesApiKey}`;
        const res = await firstValueFrom(this.http.get<{ predictions: any[] }>(url));
        if (res?.predictions && res.predictions.length > 0) {
          return res.predictions.map((p) => ({
            placeId: p.place_id,
            name: p.structured_formatting?.main_text || p.description,
            formattedAddress: p.description,
            city: p.structured_formatting?.main_text || '',
            country: p.terms?.[p.terms.length - 1]?.value || '',
            latitude: 0,
            longitude: 0,
            mapsUrl: `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p.description)}&query_place_id=${p.place_id}`,
            category: 'Google Maps Place',
          }));
        }
      } catch {
        // Fall back to verified locations
      }
    }

    // Match against verified Google Map destinations
    return VERIFIED_GOOGLE_MAP_LOCATIONS.filter(
      (loc) =>
        loc.name.toLowerCase().includes(q) ||
        loc.city.toLowerCase().includes(q) ||
        loc.formattedAddress.toLowerCase().includes(q) ||
        loc.country.toLowerCase().includes(q),
    );
  }

  getLocationByPlaceId(placeId: string): GoogleMapLocation | undefined {
    return VERIFIED_GOOGLE_MAP_LOCATIONS.find((l) => l.placeId === placeId);
  }
}
